SUMMARY = "DuDuClaw privileged system helper (reboot / poweroff / sysupdate / factory-reset / hostname)"
DESCRIPTION = "Privilege-separated root system service reached only over a \
peer-credential-verified Unix domain socket, never a network port. Runs as \
root on purpose -- it is the only process allowed to execute the narrow \
privileged verb set; duduclaw-gateway (unprivileged) talks to it over the \
socket. Source: crates/duduclaw-sysd in the main DuDuClaw repo, snapshotted \
into files/duduclaw-sysd-src by refresh-src.sh -- see that script's header \
comment for why a flattened standalone-crate snapshot is used instead of \
pointing S at the monorepo path directly."
HOMEPAGE = "https://github.com/duduclaw/duduclaw"
LICENSE = "Apache-2.0"
# md5 of the repo's own LICENSE file (copied into the snapshot by
# refresh-src.sh), not oe-core's common-licenses/Apache-2.0 -- verified by
# computing it directly (`md5 LICENSE`), not guessed/reused from another
# recipe.
LIC_FILES_CHKSUM = "file://LICENSE;md5=87e8e4a396af46e141a08fbc9f1b0455"

# Y2-1 (2026-08-25): smallest of the five duduclaw-* Rust binaries, first
# real cargo-native Yocto recipe in this layer (Y1-2 in the map's own
# numbering, done under the Y2-1 ticket). Vendoring strategy decision: per-
# crate `crate://` SRC_URI entries (duduclaw-sysd-crates.inc, generated by
# gen-crates-inc.py from the pruned Cargo.lock in files/duduclaw-sysd-src/),
# NOT a `cargo vendor` tarball blob. Chosen because oe-core's own
# cargo-update-recipe-crates.bbclass (meta/classes-recipe/) already
# establishes crate:// as the maintained-upstream pattern (librsvg is the
# real example, meta/recipes-gnome/librsvg/librsvg-crates.inc) -- a `cargo
# vendor` tarball would need its own hand-rolled refresh/checksum story with
# no oe-core tooling behind it. `cargo-bitbake` (a third option) is reported
# abandoned upstream (research/native-os-2026-08/base-os-routes-2026-08.md
# Section 3.1) so was not evaluated further.
inherit cargo cargo-update-recipe-crates

# S must be relative to UNPACKDIR, not WORKDIR, on this Yocto release (bitbake
# hard-errors otherwise: "S should be set relative to UNPACKDIR" -- caught by
# actually running do_unpack, not guessed; WORKDIR/UNPACKDIR split is a
# newer-bitbake convention that older Yocto docs/examples still show as
# WORKDIR-relative).
SRC_URI = "file://duduclaw-sysd-src"
S = "${UNPACKDIR}/duduclaw-sysd-src"

require duduclaw-sysd-crates.inc

SRC_URI += "file://duduclaw-sysd.service"

do_install:append() {
    install -d ${D}${systemd_system_unitdir}
    # UNPACKDIR, not WORKDIR -- same lesson as S above: do_unpack places every
    # local file:// SRC_URI entry (not just the one S points at) under
    # UNPACKDIR on this Yocto release. Caught by actually running do_install:
    # "install: cannot stat '.../duduclaw-sysd.service': No such file or
    # directory" with the WORKDIR-relative path.
    install -m 0644 ${UNPACKDIR}/duduclaw-sysd.service ${D}${systemd_system_unitdir}/duduclaw-sysd.service
}

inherit systemd
SYSTEMD_SERVICE:${PN} = "duduclaw-sysd.service"
SYSTEMD_AUTO_ENABLE:${PN} = "enable"

FILES:${PN} += "${systemd_system_unitdir}/duduclaw-sysd.service"
