#!/usr/bin/env python3
"""Regenerate duduclaw-sysd-crates.inc from files/duduclaw-sysd-src/Cargo.lock.

Same output format as oe-core's own `bitbake -c update_crates <recipe>`
(meta/classes-recipe/cargo-update-recipe-crates.bbclass) -- SRC_URI +=
crate://crates.io/<name>/<version> lines plus SRC_URI[<name>-<version>.
sha256sum] checksums taken straight from Cargo.lock's own `checksum` field
(the same value crates.io publishes and Cargo already verified once when it
downloaded the crate to build this lock file). Not run through bitbake
itself: nothing in this recipe's SRC_URI exists yet on the first refresh
(chicken-and-egg), so this parses the pruned Cargo.lock directly instead --
functionally identical output, verified by hand against librsvg-crates.inc's
format (meta/recipes-gnome/librsvg/librsvg-crates.inc) in the pinned oe-core
checkout.

Usage: python3 gen-crates-inc.py
(no args -- paths are fixed relative to this script, matching refresh-src.sh)
"""
import os
import sys

try:
    import tomllib
except ImportError:
    import tomli as tomllib  # type: ignore

HERE = os.path.dirname(os.path.abspath(__file__))
LOCK_PATH = os.path.join(HERE, "files", "duduclaw-sysd-src", "Cargo.lock")
OUT_PATH = os.path.join(HERE, "duduclaw-sysd-crates.inc")
ROOT_PKG = "duduclaw-sysd"


def main():
    with open(LOCK_PATH, "rb") as f:
        lock = tomllib.load(f)

    entries = []
    for pkg in lock["package"]:
        if pkg["name"] == ROOT_PKG:
            continue  # that's us, not a fetched dependency
        src = pkg.get("source", "")
        if "crates.io" not in src:
            print(f"WARNING: non-crates.io source for {pkg['name']} {pkg['version']}: {src}",
                  file=sys.stderr)
            continue
        cksum = pkg.get("checksum")
        if not cksum:
            print(f"WARNING: no checksum for {pkg['name']} {pkg['version']}", file=sys.stderr)
        entries.append((pkg["name"], pkg["version"], cksum))

    entries.sort()

    lines = [
        "# Autogenerated by gen-crates-inc.py from files/duduclaw-sysd-src/Cargo.lock\n",
        "# Re-run after refresh-src.sh whenever crates/duduclaw-sysd's deps change.\n",
        "# Same format bitbake's own `update_crates` task would produce\n",
        "# (meta/classes-recipe/cargo-update-recipe-crates.bbclass), generated here\n",
        "# directly from Cargo.lock since the recipe doesn't exist in a buildable\n",
        "# state until this file is present (chicken-and-egg).\n\n",
        'SRC_URI += " \\\n',
    ]
    for name, ver, _ in entries:
        lines.append(f"    crate://crates.io/{name}/{ver} \\\n")
    lines.append('"\n\n')
    for name, ver, cksum in entries:
        if cksum:
            lines.append(f'SRC_URI[{name}-{ver}.sha256sum] = "{cksum}"\n')

    with open(OUT_PATH, "w") as f:
        f.writelines(lines)

    print(f"Wrote {OUT_PATH}: {len(entries)} crates.io deps", file=sys.stderr)


if __name__ == "__main__":
    main()
