#!/usr/bin/env bash
# Regenerates files/duduclaw-sysd-src/ — a standalone (non-workspace) snapshot
# of crates/duduclaw-sysd, suitable for a Yocto `inherit cargo` recipe.
#
# Why a snapshot instead of pointing SRC_URI/S straight at
# crates/duduclaw-sysd/ in the monorepo: that crate's Cargo.toml uses
# `field.workspace = true` shorthand (version/edition/license/authors and
# every dependency version), which only resolves when Cargo can walk UP from
# the crate dir and find the repo-root [workspace] Cargo.toml with this crate
# listed as a member. Feeding cargo.bbclass just this one crate directory
# (not the other 24 workspace members) would make that walk-up find a
# [workspace] that's missing member directories cargo requires to exist, and
# feeding it the WHOLE monorepo would balloon SRC_URI/do_unpack for a "most
# minimal" recipe that has zero path-dependencies on any other DuDuClaw
# crate. So: flatten the workspace-shorthand fields to concrete values (taken
# from the same repo-root Cargo.toml, not invented) and ship a standalone
# Cargo.toml. Re-run this script whenever crates/duduclaw-sysd/ changes.
#
# The trimmed dependency *closure* (which crates.io packages to fetch) is
# computed separately by gen-crates-inc.py against `cargo metadata` + the
# real Cargo.lock — this script only handles OUR crate's own source + manifest.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
SRC_CRATE="$REPO_ROOT/crates/duduclaw-sysd"
OUT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/files/duduclaw-sysd-src"

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"
cp -R "$SRC_CRATE/src" "$OUT_DIR/src"
cp "$REPO_ROOT/LICENSE" "$OUT_DIR/LICENSE"

# Pull the concrete values workspace = true would have resolved to, straight
# from the repo-root Cargo.toml — never hand-typed/guessed.
WS_VERSION=$(grep -m1 '^version = ' "$REPO_ROOT/Cargo.toml" | sed -E 's/version = "(.*)"/\1/')
WS_EDITION=$(grep -m1 '^edition = ' "$REPO_ROOT/Cargo.toml" | sed -E 's/edition = "(.*)"/\1/')
WS_LICENSE=$(grep -m1 '^license = ' "$REPO_ROOT/Cargo.toml" | sed -E 's/license = "(.*)"/\1/')

cat > "$OUT_DIR/Cargo.toml" <<EOF
# Auto-generated by meta-duduclaw/recipes-duduclaw/duduclaw-sysd/refresh-src.sh
# from crates/duduclaw-sysd/Cargo.toml — DO NOT HAND-EDIT, re-run the script.
# workspace.* shorthand fields resolved to concrete values (source: repo-root
# Cargo.toml [workspace.package] / [workspace.dependencies], read at
# generation time, $(date -u +%Y-%m-%dT%H:%M:%SZ)).

# Empty [workspace] table: makes this manifest cargo-standalone even though
# it physically nests inside the DuDuClaw monorepo (which has its own
# [workspace] at the repo root) -- without this, \`cargo build\` here walks up
# and finds that outer workspace and refuses to treat this dir as its own
# package root ("current package believes it's in a workspace when it's
# not" -- cargo's own suggested fix, verified by actually hitting the error).
# Harmless / a no-op once this snapshot is copied into a Yocto WORKDIR
# outside the monorepo tree, so it stays in unconditionally.
[workspace]

[package]
name = "duduclaw-sysd"
version = "$WS_VERSION"
edition = "$WS_EDITION"
license = "$WS_LICENSE"
authors = ["DuDuClaw Contributors"]
description = "Privilege-separated root system service (reboot / poweroff / sysupdate / factory-reset / hostname) for the DuDuClaw appliance image -- reached only over a peer-credential-verified Unix domain socket, never a network port."

[[bin]]
name = "duduclaw-sysd"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
clap = { version = "4", features = ["derive"] }
uuid = { version = "1", features = ["v4", "serde"] }
anyhow = "1"
libc = "0.2"

# dev-dependencies deliberately omitted: the Yocto recipe only ever runs
# \`cargo build --release\` (cargo.bbclass), never \`cargo test\` -- keeping
# them out shrinks the fetched crate closure and matches what
# gen-crates-inc.py already computes (it only walks Normal/Build dep-kinds).

[lints.rust]
unsafe_code = "warn"
EOF

# Cargo.lock: start from the real workspace lock (so every version pin
# matches what's actually developed/tested against, never re-resolved to
# something newer), then let `cargo generate-lockfile` PRUNE it down to only
# the packages reachable from the flattened, standalone Cargo.toml above.
#
# This step is required, not cosmetic: cargo.bbclass builds with `--frozen`
# (= --locked --offline), and `--locked` refuses to silently drop unreachable
# [[package]] entries at build time -- verified by hitting it directly:
# `cargo build --release --locked` against the full 1059-package workspace
# lock errored with "cannot update the lock file ... because --locked was
# passed to prevent this". A plain `cargo build --release` (no --locked) DID
# succeed and rewrote Cargo.lock down to duduclaw-sysd's real closure (98
# packages including itself), keeping every version pin IDENTICAL to the
# workspace lock (verified: clap stayed 4.6.1, tokio stayed 1.52.0, etc.).
#
# Deliberately NOT `cargo generate-lockfile` here -- tried that first and it
# re-resolved to "latest Rust-compatible versions" instead of preserving the
# existing pins (clap silently jumped 4.6.1 -> 4.6.6), which is exactly what
# this script must never do: the whole point is shipping the SAME versions
# already developed/tested against, just pruned to duduclaw-sysd's closure.
# A real `cargo build` respects the existing lock far more conservatively
# (only touches entries it must), so that's what prunes it here; the
# resulting target/ is build waste, discarded immediately after.
cp "$REPO_ROOT/Cargo.lock" "$OUT_DIR/Cargo.lock"
(cd "$OUT_DIR" && cargo build --release --offline >/dev/null 2>&1 || cd "$OUT_DIR" && cargo build --release >/dev/null)
rm -rf "$OUT_DIR/target"

echo "Wrote $OUT_DIR (Cargo.toml flattened, Cargo.lock pruned to $(grep -c '^name = ' "$OUT_DIR/Cargo.lock") packages, src/ synced)"
