use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Role of a turn in the MDP trajectory (Agent-R1 framework).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TurnRole {
    /// Agent-generated action (tool call or text response). Loss is computed on these.
    AgentAction,
    /// Environment feedback (tool result, system message). Loss masked.
    EnvironmentFeedback,
    /// User message. Loss masked.
    UserMessage,
}

/// A recorded tool call within a turn.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallRecord {
    pub name: String,
    pub arguments: serde_json::Value,
    pub result: serde_json::Value,
    pub success: bool,
}

/// A single turn in the RL trajectory.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RLTurn {
    pub role: TurnRole,
    pub content: String,
    pub tool_calls: Option<Vec<ToolCallRecord>>,
    pub token_count: u32,
    /// Whether this turn was generated by the agent (for loss masking).
    pub is_agent_generated: bool,
}

/// A complete RL trajectory ready for training.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RLTrajectory {
    pub trajectory_id: String,
    pub agent_id: String,
    pub model_id: String,
    pub turns: Vec<RLTurn>,
    pub total_tokens: u64,
    pub outcome_reward: f64,
    pub metadata: HashMap<String, serde_json::Value>,
    pub created_at: DateTime<Utc>,
}

impl RLTrajectory {
    /// Count agent-generated tokens (for loss computation).
    pub fn agent_tokens(&self) -> u64 {
        self.turns
            .iter()
            .filter(|t| t.is_agent_generated)
            .map(|t| t.token_count as u64)
            .sum()
    }

    /// Count environment tokens (masked from loss).
    pub fn environment_tokens(&self) -> u64 {
        self.turns
            .iter()
            .filter(|t| !t.is_agent_generated)
            .map(|t| t.token_count as u64)
            .sum()
    }

    /// Count total tool calls across all turns.
    pub fn total_tool_calls(&self) -> usize {
        self.turns
            .iter()
            .filter_map(|t| t.tool_calls.as_ref())
            .map(|tc| tc.len())
            .sum()
    }

    /// Count successful tool calls.
    pub fn successful_tool_calls(&self) -> usize {
        self.turns
            .iter()
            .filter_map(|t| t.tool_calls.as_ref())
            .flat_map(|tc| tc.iter())
            .filter(|tc| tc.success)
            .count()
    }
}

/// Export format for trajectories.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExportFormat {
    /// JSON Lines (one trajectory per line).
    Jsonl,
}
