SUMMARY = "DuDuClaw OS native agent-first shell (gpui client for duduclaw-comp)"
DESCRIPTION = "${SUMMARY} -- the gpui-based desktop UI (Shell-S0..S5 series) \
that runs as duduclaw-comp's Wayland client, forming the \"開機即殼\" pair \
(commercial/docs/MAP-agent-native-os-2026-08.md destination judgment ①/⑤). \
Source: a TWO-crate snapshot of crates/duduclaw-shell + crates/duduclaw-native-gui \
(the latter is a sibling path dependency, not a workspace member -- see \
refresh-src.sh's own header comment for why two destsuffixes, not a \
mini-workspace the way duduclaw-cli's recipe does it), generated by \
refresh-src.sh. Git-sourced deps (the zed monorepo's 23 gpui-family member \
crates + wasm_thread + zed-font-kit + zed-scap) are in \
duduclaw-shell-git-deps.inc, generated by gen-git-deps.py -- see that \
script's header comment for the subpath/destsuffix/name mechanism this \
relies on (bitbake git fetcher dedup + cargo_common.bbclass's \
cargo_common_do_patch_paths [patch] generation)."
HOMEPAGE = "https://github.com/duduclaw/duduclaw"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://LICENSE;md5=87e8e4a396af46e141a08fbc9f1b0455"

# Y3-1 (2026-08-25) DEPENDS, empirically verified minimal -- NOT copied from
# duduclaw-comp's own (still build-unverified as of this recipe's writing)
# DEPENDS comment. `crates/duduclaw-shell/BUILD-LINUX.md` (Shell-S2,
# 2026-08-20) already did the real work this recipe leans on: a Docker
# `rust:bookworm` cold-compile with a deliberately generous initial package
# guess, then DELETED cmake and libssl-dev and rebuilt from an empty
# target/ -- the trimmed build produced a byte-identical binary (same build
# ID), proving neither was ever linked in. What's left is exactly:
#   - pkg-config + libwayland-dev -> pkgconfig-native (inherit, below) + wayland
#   - libxkbcommon-dev -> libxkbcommon
#   - libfontconfig1-dev -> fontconfig (pulls freetype transitively on
#     Debian; oe-core's fontconfig_2.17.1.bb DEPENDS on freetype directly,
#     same effective closure -- both confirmed present as oe-core recipes)
# No Vulkan/EGL/GL headers, no mesa, no libdrm, no libinput, no seatd DEPENDS
# here (unlike duduclaw-comp): gpui_wgpu's wgpu backend only codegens FFI
# bindings at compile time and dlopen()s the real driver .so at runtime
# (BUILD-LINUX.md's own "No Vulkan/EGL/GL headers are needed at build time"
# finding, cross-checked against the identical reasoning duduclaw-comp's own
# recipe comment gives for smithay's EGL path) -- those libraries only need
# to exist in the IMAGE at runtime (see duduclaw-image.bb), not in this
# recipe's DEPENDS/recipe-sysroot at build time.
DEPENDS = "wayland libxkbcommon fontconfig"
inherit cargo cargo-update-recipe-crates pkgconfig

# S is UNPACKDIR/duduclaw-shell-src, NOT WORKDIR-relative -- same UNPACKDIR
# vs WORKDIR gotcha duduclaw-sysd's own recipe comment documents (hit for
# real there first: do_install's `install` step needs UNPACKDIR too, see
# below).
SRC_URI = "file://duduclaw-shell-src file://duduclaw-native-gui"
S = "${UNPACKDIR}/duduclaw-shell-src"

require duduclaw-shell-crates.inc
require duduclaw-shell-git-deps.inc

# Q1 (2026-08-24) shipping gate: this crate's own Cargo.toml `[features]
# default = []` already matches the appliance's desired build (no debug
# affordances reachable) -- plain `cargo build`, no CARGO_BUILD_FLAGS
# override needed, same as duduclaw-comp's own recipe comment for the
# identical reason.

# Y2-3's duduclaw-cli recipe hit a buildpaths QA failure from a vendored
# crate's C build.rs (tree-sitter) leaking ${WORKDIR}/sources/cargo_home
# paths into .rodata via __FILE__ macro expansion. This crate's own
# Cargo.lock has no tree-sitter (verified: `grep tree-sitter
# files/duduclaw-shell-src/Cargo.lock` -- zero hits), but yeslogic-
# fontconfig-sys/freetype-sys (pulled in by zed-font-kit, both C-linkage via
# the `cc` crate same as tree-sitter was) are a plausible same-shape risk
# that was NOT ruled out ahead of time -- left for the real bitbake build to
# either confirm clean or reveal, rather than pre-emptively applying
# duduclaw-cli's CFLAGS/CXXFLAGS fix on a guess. If do_package_qa's
# `buildpaths` check fires here, mirror duduclaw-cli_1.62.0.bb's
# `CFLAGS:append`/`CXXFLAGS:append` fix verbatim -- same root cause, same
# remedy, see that recipe's own comment for the full mechanism.

do_install:append() {
    install -d ${D}${systemd_system_unitdir}
    install -m 0644 ${UNPACKDIR}/duduclaw-kiosk.service ${D}${systemd_system_unitdir}/duduclaw-kiosk.service
    install -d ${D}${sbindir}
    install -m 0755 ${UNPACKDIR}/duduclaw-kiosk-launch.sh ${D}${sbindir}/duduclaw-kiosk-launch.sh
}

SRC_URI += "file://duduclaw-kiosk.service file://duduclaw-kiosk-launch.sh"

inherit systemd useradd
SYSTEMD_SERVICE:${PN} = "duduclaw-kiosk.service"
SYSTEMD_AUTO_ENABLE:${PN} = "enable"

FILES:${PN} += "${systemd_system_unitdir}/duduclaw-kiosk.service ${sbindir}/duduclaw-kiosk-launch.sh"

# duduclaw-kiosk system user -- mirrors appliance/postinst.d/
# 20-users-and-units.sh's `useradd -d /data/duduclaw-kiosk -G video,render,
# audio` EXCEPT the group list, which is a REAL, VERIFIED divergence from
# the Debian line, not a copy-paste: oe-core's seatd_0.9.3.bb installs
# seatd's UPSTREAM contrib/systemd/seatd.service verbatim
# (`GROUPADD_PARAM:${PN} = "-r seat"`), NOT Debian's own patched unit
# (`debian/seatd.service`/`debian/seatd.default`: "seatd -g video"). This
# recipe's kiosk user therefore joins the `seat` group, not `video` --
# joining `video` here would grant a group seatd on THIS distro never
# checks, silently failing to connect to its control socket. `render` is
# kept for the same reason the Debian line keeps it: Chromium-shaped GPU
# clients open /dev/dri/renderD* directly (a plain filesystem open, not
# brokered through seatd) -- duduclaw-shell's own wgpu backend does the
# same thing. No `audio` group / PipeWire wiring in this Y3-1 round (no
# PipeWire recipe in this image yet) -- tracked as an explicit gap, see the
# image recipe's own comment.
USERADD_PACKAGES = "${PN}"
USERADD_PARAM:${PN} = "--system --home-dir /data/duduclaw-kiosk --no-create-home --shell /sbin/nologin --groups video,render,seat duduclaw-kiosk"

# RDEPENDS on duduclaw-comp (the systemd unit's ExecStart target) and seatd
# (the `seat` supplementary group referenced above must exist by the time
# THIS package's useradd postinst runs -- rootfs-time postinst execution
# order follows the package manager's dependency resolution, same as any
# other on-target install ordering, so this RDEPENDS is load-bearing for
# useradd's `--groups seat` to succeed, not just documentation of a runtime
# want).
#
# `bash` is explicitly required too: duduclaw-kiosk-launch.sh uses bash-only
# syntax (`[[ ]]`, `shopt -s nullglob`, C-style `for (( ))` loops) and
# core-image-minimal's default /bin/sh is busybox ash, which does not
# support any of these -- unlike the Debian appliance line, bash is not a
# given on this image and has to be pulled in explicitly.
RDEPENDS:${PN} += "duduclaw-comp seatd bash"
