#!/usr/bin/env python3
"""Regenerate duduclaw-shell-crates.inc from files/duduclaw-shell-src/Cargo.lock's
crates.io-sourced packages -- the git-sourced ones (gpui/zed monorepo members,
wasm_thread, zed-font-kit, zed-scap) are handled separately by
gen-git-deps.py -> duduclaw-shell-git-deps.inc, same split duduclaw-comp's
own gen-crates-inc.py already warns-and-skips for (that script had zero
git/path entries to skip; this one has 26, hence the separate companion
script instead of just accepting the warnings).
"""
import os
import sys

try:
    import tomllib
except ImportError:
    import tomli as tomllib  # type: ignore

HERE = os.path.dirname(os.path.abspath(__file__))
LOCK_PATH = os.path.join(HERE, "files", "duduclaw-shell-src", "Cargo.lock")
OUT_PATH = os.path.join(HERE, "duduclaw-shell-crates.inc")
ROOT_PKGS = {"duduclaw-shell", "duduclaw-native-gui"}


def main():
    with open(LOCK_PATH, "rb") as f:
        lock = tomllib.load(f)

    entries = []
    git_count = 0
    for pkg in lock["package"]:
        if pkg["name"] in ROOT_PKGS:
            continue
        src = pkg.get("source", "")
        if src.startswith("git+"):
            git_count += 1
            continue
        if "crates.io" not in src:
            print(f"WARNING: unexpected source for {pkg['name']} {pkg['version']}: {src!r}",
                  file=sys.stderr)
            continue
        cksum = pkg.get("checksum")
        if not cksum:
            print(f"WARNING: no checksum for {pkg['name']} {pkg['version']}", file=sys.stderr)
        entries.append((pkg["name"], pkg["version"], cksum))

    entries.sort()

    lines = [
        "# Autogenerated by gen-crates-inc.py from files/duduclaw-shell-src/Cargo.lock\n",
        "# Re-run after refresh-src.sh whenever crates/duduclaw-shell's or\n",
        "# crates/duduclaw-native-gui's deps change. Git-sourced deps (gpui/zed monorepo,\n",
        "# wasm_thread, zed-font-kit, zed-scap) are in duduclaw-shell-git-deps.inc instead\n",
        "# (see gen-git-deps.py) -- not missing from here by accident.\n\n",
        'SRC_URI += " \\\n',
    ]
    for name, ver, _ in entries:
        lines.append(f"    crate://crates.io/{name}/{ver} \\\n")
    lines.append('"\n\n')
    for name, ver, cksum in entries:
        if cksum:
            lines.append(f'SRC_URI[{name}-{ver}.sha256sum] = "{cksum}"\n')

    with open(OUT_PATH, "w") as f:
        f.writelines(lines)

    print(f"Wrote {OUT_PATH}: {len(entries)} crates.io deps ({git_count} git deps skipped, "
          f"see duduclaw-shell-git-deps.inc)", file=sys.stderr)


if __name__ == "__main__":
    main()
