// @ts-check
import fs from 'node:fs';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { docsBase } from './base.mjs';

/**
 * The "getting started" group is a curated list of existing pages, so its
 * slugs are generated by scripts/sync-docs.mjs (which runs before every dev
 * and build) rather than hard-coded here: Starlight refuses to build on a
 * sidebar slug with no page, and a checkout without the platform docs must
 * still produce a site.
 */
const startLinks = (() => {
  try {
    return JSON.parse(fs.readFileSync(new URL('./src/start-links.json', import.meta.url), 'utf8'));
  } catch {
    return [];
  }
})();

/**
 * The docs site is served as a sub-path of the main DuDuClaw OS site
 * (website/ at the repo root is copied to `_site/`, this build to
 * `_site/docs/`). `SITE_URL` is set by CI once the real domain exists.
 */
const site = process.env.SITE_URL || 'https://example.invalid';

/**
 * URL prefix — `/docs` on a custom domain or user page, `/<repo>/docs` on a
 * project page. See base.mjs. Nothing in the site hard-codes this value:
 * page-to-page links come from Starlight's own routing, and the landing pages
 * build their hrefs from `import.meta.env.BASE_URL`.
 */
const base = docsBase();

/** Sidebar group labels, root locale first, translations alongside. */
const t = (zh, en, ja) => ({ label: zh, translations: { en, ja } });

export default defineConfig({
  site,
  base,
  integrations: [
    starlight({
      title: {
        'zh-TW': 'DuDuClaw OS 文件',
        en: 'DuDuClaw OS Docs',
        ja: 'DuDuClaw OS ドキュメント',
      },
      description:
        'DuDuClaw OS 與 DuDuClaw 平台的公開文件：安裝、桌面、AI runtime、架構與規格。',
      logo: {
        src: './src/assets/duduclaw-mark-circle.svg',
        alt: 'DuDuClaw',
      },
      favicon: '/favicon.svg',
      customCss: ['./src/styles/custom.css'],
      // No "edit this page" link and no GitHub icons anywhere in the chrome:
      // the docs live on our own domain. The only header link is the one back
      // to the main site, rendered by the SiteLink component below.
      components: {
        SocialIcons: './src/components/SiteLink.astro',
      },
      head: [
        {
          tag: 'link',
          attrs: { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
        },
        {
          tag: 'link',
          attrs: { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: true },
        },
        {
          tag: 'link',
          attrs: {
            rel: 'stylesheet',
            href: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&family=Noto+Sans+TC:wght@400;500;700&display=swap',
          },
        },
      ],
      defaultLocale: 'root',
      locales: {
        root: { label: '繁體中文', lang: 'zh-TW' },
        en: { label: 'English', lang: 'en' },
        ja: { label: '日本語', lang: 'ja' },
      },
      expressiveCode: {
        themes: ['github-dark', 'github-light'],
        styleOverrides: { borderRadius: '10px' },
      },
      pagination: true,
      sidebar: [
        ...(startLinks.length
          ? [
              {
                ...t('入門與安裝', 'Getting started', 'はじめに'),
                items: startLinks.map((slug) => ({ slug })),
              },
            ]
          : []),
        {
          ...t('功能', 'Features', '機能'),
          collapsed: true,
          items: [{ autogenerate: { directory: 'features' } }],
        },
        {
          ...t('指南', 'Guides', 'ガイド'),
          collapsed: true,
          items: [{ autogenerate: { directory: 'guides' } }],
        },
        {
          ...t('架構', 'Architecture', 'アーキテクチャ'),
          collapsed: true,
          items: [{ autogenerate: { directory: 'architecture' } }],
        },
        {
          ...t('規格', 'Specifications', '仕様'),
          collapsed: true,
          items: [{ autogenerate: { directory: 'spec' } }],
        },
        {
          ...t('API', 'API', 'API'),
          collapsed: true,
          items: [{ autogenerate: { directory: 'api' } }],
        },
        {
          ...t('OS 專案', 'OS project', 'OS プロジェクト'),
          collapsed: true,
          items: [{ autogenerate: { directory: 'os', collapsed: true } }],
        },
      ],
    }),
  ],
});
