// DuDuClaw Native GUI — Phase 1a.
//
// Phase 0a (see git history for the original single-file version this
// replaced) proved gpui builds + runs on this machine and that a background
// thread can bridge a WebSocket connection to the local gateway into the
// gpui UI thread. Phase 1a builds the first real UI on top of that
// foundation: language-picker-first entry → login screen → app shell
// (sidebar + routing + content area).
//
// Design language: MDS (Multica-derived Design System) — re-skinned from
// the original "Calm Glass" pass per client feedback ("版面/配色/間距/字體都
// 不對", 2026-08). Source of truth: `commercial/docs/multica-redesign-
// spec.md` + `web/src/index.css`'s shipped OKLCH tokens, converted to sRGB
// hex in `theme.rs` (see that file's module doc comment for the conversion
// methodology and verification). NOT `web/DESIGN.md` / the root `CLAUDE.md`
// "Design Context" section anymore — those describe the superseded Calm
// Glass language.
//
// ── gpui API gotchas learned so far (do NOT rediscover these) ───────────
// Verified against the local gpui git checkout
// (~/.cargo/git/checkouts/zed-*, rev 7a7c3e1, 2026-08-19):
//   - Entry point is `gpui_platform::application()`, NOT `Application::new()`.
//   - `Styled` box methods (`p_*`, `gap_*`, `size_*`, `w_*`, `h_*`, `m_*`,
//     `rounded_*`) are a FIXED Tailwind-preset ramp generated by
//     `gpui_macros::style_helpers!()` (`crates/gpui_macros/src/styles.rs`
//     `box_style_suffixes()` / `corner_suffixes()`) — there is no free-form
//     `.p(px(24.))`. But the SAME macros also emit an arbitrary-value
//     "custom setter" per prefix (`.w(px(480.))`, `.pl(px(26.))`,
//     `.text_size(px(15.))`, `.bg(rgb(...))`, `.text_color(rgb(...))`,
//     `.border_color(rgb(...))` — these take real `Pixels`/`Into<Hsla>`
//     values). `crates/gpui/examples/popover.rs` and `focus_visible.rs` are
//     the clearest references for which is which.
//   - `cx.spawn(async move |cx: &mut AsyncApp| ...)` for background-thread
//     bridges (see `ws_status.rs` + the poll loop below); update entities
//     via `WindowHandle::update` / `Entity::update` + `cx.notify()`.
//   - `cx.listener(|this: &mut V, event, window, cx: &mut Context<V>| ...)`
//     (`crates/gpui/src/app/context.rs`) is how a click/key handler gets
//     mutable access to view state — it downgrades+upgrades the entity, so
//     it's safe to store on `Div` builders directly via `.on_click(...)`.
//   - `.id("stable-id")` is required before `.on_click(...)` (every
//     interactive-but-clickable example does this;
//     `StatefulInteractiveElement` needs an `ElementId`).
//   - A `&mut Context<V>` is NOT `Copy`, so it cannot be captured into a
//     closure that runs more than once (e.g. `Iterator::map` building a
//     `Vec` of rows) — use a plain `for` loop instead (each iteration
//     re-borrows fresh). See `screens/language_picker.rs` and
//     `screens/shell.rs` for the pattern.
//   - No CSS `backdrop-filter` equivalent exists in gpui's style system
//     (only `BoxShadow::blur_radius` for drop shadows) — MDS's own alpha-
//     modifier tokens (`bg-foo/NN`) are approximated with translucent solid
//     colors (`theme::alpha`), not a true blur, but MDS itself barely leans
//     on blur outside the Dialog overlay, which Phase 1a doesn't implement.
//   - `Entity<T: Render>` implements `IntoElement` directly, so a child
//     entity (e.g. a `TextField`) can be passed straight to `.child(...)`.
//   - `Styled::text_color()` / `::border_color()` take `impl Into<Hsla>` —
//     `Rgba` (what `rgb()`/`rgba()`/`theme::alpha()` return) satisfies that
//     bound directly, so pass it AS-IS. Calling `.into()` on it yourself
//     makes the target ambiguous (`Rgba` also implements `Into<Fill>`,
//     `Into<Background>`, `Into<u32>`, `Into<HighlightStyle>`) and fails to
//     compile with "type annotations needed" UNLESS something else in the
//     same expression anchors the type (e.g. the other arm of an `if/else`
//     already being a concrete `Hsla`, as in `text_field.rs`'s border color).
//   - `.id(...)` changes an element's concrete type from `Div` to
//     `Stateful<Div>` — a helper function that calls `.id(...)` and is
//     later used with `.on_click(...)` must declare `-> Stateful<Div>`, not
//     `-> Div`, or the return-type check fails (`screens/language_picker.rs`
//     `locale_card`, `screens/shell.rs` `nav_row`).
//
// First build after adding deps is slow; incremental builds are seconds.
// ALWAYS build/run with the arm64 toolchain pinned by `rust-toolchain.toml`
// (1.97.1) — plain `cargo`/`rustc` on PATH is Homebrew's x86_64 build and
// silently produces an x86_64 binary that panics on architecture-sensitive
// build scripts deep in gpui's dependency tree (`media`'s bindgen step,
// which dlopens Xcode's arm64-only libclang.dylib).
//
// IMPORTANT (found the hard way in this session — the crate's own
// documented fix, `rustup run stable-aarch64-apple-darwin cargo build`,
// does NOT reliably work): `rustup run <toolchain> cargo` only guarantees
// the *cargo* binary itself is correct — cargo then resolves `rustc` via a
// bare PATH lookup (`Command::new("rustc")`, no absolute path), and if a
// Homebrew/system `rustc` sits earlier on PATH than the rustup shim dir
// (true on this machine: `/usr/local/bin` before `~/.cargo/bin`), the
// ACTUAL compiler used for build scripts is silently the wrong x86_64 one
// even though `cargo -vV` reports the right host. Symptom: `media`'s build
// script panics with "libclang ... incompatible architecture (have arm64,
// need x86_64)" — the smoking gun is `file target/debug/build/media-*/
// build-script-build` reporting `x86_64` executable. Root-caused by running
// `cargo build -vv` and finding `HOST=x86_64-apple-darwin` / bare
// `RUSTC=rustc` in the env cargo hands to the build script. The reliable
// fix, used for every build/run in this session:
//   export PATH="$HOME/.rustup/toolchains/1.97.1-aarch64-apple-darwin/bin:$PATH"
//   export RUSTC="$HOME/.rustup/toolchains/1.97.1-aarch64-apple-darwin/bin/rustc"
//   cargo build   # (now resolves correctly, arm64 end to end)
// After a wrong-arch attempt, `rm -rf target` before switching — the two
// architectures' build-script artifacts share the same `target/debug/`
// directory (no explicit `--target` is passed) and do not safely coexist.

mod api;
mod chat_protocol;
mod chat_ws;
mod config;
mod gateway_switch;
mod i18n;
mod native_menu;
mod nav;
mod rpc;
mod screens;
mod sidecar;
mod sidecar_target;
mod text_field;
mod updater;
mod ws_status;

// Shell-S0: `theme`/`mds_gpui` moved to this crate's own `lib.rs` so the new
// `duduclaw-shell` crate can reuse them — see that file's doc comment. This
// `use` re-binds both names into THIS bin crate's root module namespace, so
// every existing `crate::theme::...` / `crate::mds_gpui::...` reference
// throughout `screens/`, `text_field.rs`, `native_menu.rs`, `nav.rs`,
// `ws_status.rs` keeps resolving unchanged (a private
// `use` at the crate root is visible to every descendant module in the same
// crate — no signature/call-site changes needed anywhere else).
// D3-b (2026-08-23): `ime_input` joined them there for the same reason —
// `duduclaw-shell` now drives the same widget. Its own `crate::theme`
// references keep resolving because it is compiled as part of the lib now.
use duduclaw_native_gui::{ime_input, mds_gpui, theme};

use std::sync::mpsc;
use std::sync::Arc;
use std::time::Duration;

use gpui::{prelude::*, px, App, Bounds, Context, Entity, Render, SharedString, Window, WindowBounds, WindowOptions};
use gpui_platform::application;
use tokio::sync::mpsc as tokio_mpsc;

use i18n::Locale;
use text_field::TextField;
use ws_status::{Command as SessionCommand, Event as SessionEvent, WsConnState};

/// Which of the three Phase 1a screens is currently showing.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Screen {
    Language,
    Login,
    Shell,
}

pub struct RootView {
    screen: Screen,
    locale: Locale,
    ws_state: WsConnState,
    email_field: Entity<TextField>,
    password_field: Entity<TextField>,
    /// Currently-selected sidebar nav item id (see `nav.rs`), used once
    /// `screen == Screen::Shell`.
    active_page: &'static str,
    /// S4a: which of the 13 static prototype pages is selected inside the
    /// "設計稿" design gallery (`screens/prototypes/mod.rs`). Only
    /// meaningful when `active_page == "designGallery"`; otherwise unused —
    /// initialized to the gallery's first entry either way.
    active_prototype: &'static str,
    /// P0-1: whether `screens/shell.rs`'s Column 1 (the area rail) is
    /// hidden. Toggled by the macOS menu bar's View ▸ Show/Hide Sidebar
    /// action (`native_menu.rs`) — no other UI trigger exists yet, so on
    /// non-macOS builds this stays permanently `false` (honest stub: no
    /// persistence either, matches this crate's existing `jwt`/
    /// `refresh_token` "S2 scope stops here" precedent above).
    sidebar_collapsed: bool,
    /// Command channel into the background session manager (`ws_status.rs`)
    /// — cloned into click handlers that need to trigger a login or a WS
    /// (re)connect.
    session_tx: tokio_mpsc::UnboundedSender<SessionCommand>,
    /// Access token, in memory only. S2 scope stops here deliberately: no
    /// disk persistence, no refresh timer — see this crate's final S2
    /// report for the explicit S3+ "honest stub" callout on refresh-token
    /// handling. Read by any page needing an authenticated REST call
    /// alongside the WS session — `screens::device_backup`'s download-URL
    /// builder was the first consumer (S5b1-A), `screens::files`'s
    /// `Command::RestGet`/preview-download URLs (WP-S5b2-F) the second; the
    /// `#[allow(dead_code)]` this field used to carry (accurate only up
    /// through S2) is gone now that it has real readers.
    jwt: Option<String>,
    /// Refresh token, in memory only (task item 5: "本階段只存於記憶體、不做自動
    /// refresh timer"). S2 captures it so it exists when an S3+ refresh
    /// timer is wired up, but nothing reads it yet — the 30-min access
    /// token this crate currently obtains simply goes stale unrefreshed on
    /// a long-running session, exactly like the "honest stub" this field's
    /// name promises.
    #[allow(dead_code)]
    refresh_token: Option<String>,
    /// True while a `login`/local-session HTTP call is in flight — drives
    /// the submit button's loading/disabled state.
    login_loading: bool,
    /// Localized error line shown under the login form, if the last
    /// attempt failed.
    login_error: Option<SharedString>,
    /// S4: the chat page's own state (messages, connection status, the
    /// IME-capable composer entity, ...) — see `screens/chat.rs`'s doc
    /// comment for why this is one bundled field, not a dozen flat ones.
    chat: screens::chat::ChatState,
    /// The logged-in user's `display_name` (`api::AuthUser`), captured from
    /// the local-session/login response for the dashboard greeting line.
    /// `None` until a session actually resolves; the greeting falls back to
    /// a generic name rather than showing nothing (see `screens::dashboard::
    /// greeting_name`).
    display_name: Option<String>,
    /// WP-S5b2-E (2026-08-21): the logged-in user's own id (`api::AuthUser::
    /// id`), captured alongside `display_name` at the exact same two call
    /// sites. Added for `screens::widgets`'s "我的" vs "團隊分享" tab split
    /// (`created_by_user == this id`), which `web/src/pages/WidgetsPage.tsx`
    /// does the same way via `useAuthStore`'s `user.id` — this crate has no
    /// such store yet, so the id rides on `RootView` directly, same shape
    /// `display_name` already established rather than inventing a second
    /// mechanism. `None` until a session resolves, same honest-stub
    /// semantics as `display_name`.
    user_id: Option<String>,
    /// WP-gpui-spike-T7 (2026-08-21): debug-only Chromium-risk-page
    /// feasibility spike state (`screens::spike_t7`) — see that module's doc
    /// comment. Always constructed (same "unconditional field, only
    /// meaningful on one debug page" shape as `active_prototype` above), so
    /// there's no `Option` to unwrap when `DUDUCLAW_NATIVE_GUI_DEBUG_PAGE=
    /// spike_t7` lands on it.
    spike_t7: screens::spike_t7::SpikeT7State,
    /// WP-C-M2 (2026-08-22): this launch's local gateway sidecar manager.
    /// Always constructed, regardless of whether the CURRENT target is
    /// local (see `resolve_startup_gateway`'s doc comment) — `screens::
    /// gateway_picker`'s "切換到本機" action needs something to call
    /// `.start()` on even when today's session began pointed at a remote
    /// gateway or never spawned anything (attached to one already running).
    sidecar: Arc<sidecar::SidecarManager>,
    /// The gateway-picker page's manual-entry field (`screens::
    /// gateway_picker`) — lives here rather than inside a page-local
    /// `Global`, matching `email_field`/`password_field`'s placement: this
    /// is a real gpui text-input `Entity` that must be constructed once
    /// with `&mut App` (available at `RootView` construction time, inside
    /// `cx.open_window`'s closure), not per-render.
    gateway_manual_field: Entity<TextField>,
    /// True while a gateway-picker health-check/connect round trip is in
    /// flight — drives the manual-entry connect button's loading/disabled
    /// state, same role `login_loading` plays for the login form.
    gateway_connecting: bool,
    /// Localized-ish error line shown under the gateway-picker manual entry
    /// after a failed connect attempt (health-check failure, or a locally-
    /// rejected malformed URL). `None` when nothing has failed yet.
    gateway_connect_error: Option<SharedString>,
    /// WP-C-M3: this launch's self-update manager for the `DuDuClaw.app`
    /// bundle itself — see `updater/mod.rs`'s module doc comment for why
    /// this is a THIRD, independent thing from `sidecar` (which manages the
    /// gateway subprocess) and from `screens::about`'s existing
    /// `system.check_update` line (which checks the gateway's OWN CLI-binary
    /// update channel). Always constructed, same "cheap to always have,
    /// only meaningful on one page" shape `sidecar`/`spike_t7` already use.
    app_updater: Arc<updater::UpdaterManager>,
}

impl RootView {
    /// Apply one event from the background session manager. Pulled out of
    /// the `cx.spawn` poll loop in `main()` so the state-transition logic
    /// is unit-testable-in-spirit (pure `&mut self` mutation) and readable
    /// in one place rather than inline in a closure.
    fn handle_session_event(&mut self, event: SessionEvent) {
        match event {
            SessionEvent::LocalSessionOk(resp) => {
                // Guard against the (practically impossible, but cheap to
                // guard) race where a manual login already completed
                // before this boot-time probe resolved — never let a stale
                // local-session token clobber a fresh interactive login.
                if self.jwt.is_some() {
                    return;
                }
                self.jwt = Some(resp.access_token.clone());
                self.refresh_token = Some(resp.refresh_token);
                self.screen = Screen::Shell;
                self.login_error = None;
                // S4b: for the dashboard greeting line — see that field's
                // own doc comment.
                self.display_name = Some(resp.user.display_name.clone());
                // WP-S5b2-E: see `user_id`'s own doc comment.
                self.user_id = Some(resp.user.id.clone());
                // S4: the chat socket authenticates eagerly right alongside
                // the main `/ws`, same timing — by the time a user actually
                // navigates to the chat page it's normally already
                // connected, not connecting-on-first-open.
                self.chat.connect(resp.access_token.clone());
                let _ = self.session_tx.send(SessionCommand::ConnectWs {
                    jwt: resp.access_token,
                });
            }
            SessionEvent::LocalSessionUnavailable => {
                // Silent — matches `auth-store.ts`'s `tryLocalSession()`
                // policy exactly: a refusal here is expected on every
                // install that isn't a Personal loopback box, and must
                // never surface as an error. Whatever screen locale
                // resolution already picked (Language or Login) just stays.
            }
            SessionEvent::LoginOk(resp) => {
                self.jwt = Some(resp.access_token.clone());
                self.refresh_token = Some(resp.refresh_token);
                self.screen = Screen::Shell;
                self.login_loading = false;
                self.login_error = None;
                self.display_name = Some(resp.user.display_name.clone());
                self.user_id = Some(resp.user.id.clone());
                self.chat.connect(resp.access_token.clone());
                let _ = self.session_tx.send(SessionCommand::ConnectWs {
                    jwt: resp.access_token,
                });
            }
            SessionEvent::LoginErr(err) => {
                self.login_loading = false;
                // `Other`'s `detail` is diagnostic-only (raw server error
                // text / reqwest error message) — never shown to the user
                // (the UI only ever gets the localized `{code}` message),
                // but it must not be silently dropped either (honest-
                // reporting convention: a failure's detail belongs in the
                // logs even when the UI necessarily shows a generic line).
                if let crate::api::AuthError::Other { status, detail } = &err {
                    eprintln!("[auth] login failed: status={status:?} detail={detail}");
                }
                let (key, code) = err.i18n_key_and_code();
                self.login_error = Some(if code.is_empty() {
                    i18n::t(self.locale, key)
                } else {
                    i18n::t1(self.locale, key, "code", &code)
                });
            }
            SessionEvent::WsState(state) => {
                self.ws_state = state;
            }
            SessionEvent::WsAuthFailed => {
                // Terminal per `ws_status.rs`'s own contract: the manager
                // has already stopped retrying with this (rejected) token.
                // Recovery requires a fresh `Login`, so kick the user back
                // to the login form rather than spinning silently.
                self.jwt = None;
                self.refresh_token = None;
                self.ws_state = WsConnState::Disconnected;
                self.screen = Screen::Login;
                self.login_error = Some(i18n::t(self.locale, "login.error.sessionExpired"));
                // The chat socket's JWT is now stale too — tear it down
                // rather than let it keep retrying a token the server just
                // rejected on the main `/ws` (same "auth 失敗 不無限重試"
                // reasoning `ws_status.rs` already applies to itself).
                self.chat.disconnect();
            }
            SessionEvent::ServerEvent { event, payload } => {
                // S4: no page subscribes to any particular server-pushed
                // event yet (the RPC call layer is new infrastructure this
                // pass, not consumed by the chat screen — that talks over
                // its own separate `/ws/chat` socket, see `chat_ws.rs`).
                // Logged rather than silently dropped so the plumbing is
                // observably alive even with zero consumers today.
                eprintln!("[main] server event on main /ws (no subscriber yet): {event} {payload}");
            }
        }
    }

    /// Apply one event from the background chat session manager
    /// (`chat_ws.rs`). Mirrors `handle_session_event`'s shape/placement —
    /// pulled out of the poll loop for the same readability reason.
    fn handle_chat_event(&mut self, event: chat_ws::Event) {
        self.chat.apply(event);
    }
}

// WP-C-M2: `apply_gateway_switch`/`switch_to_local`/`begin_manual_connect`
// (a second `impl RootView` block) plus `resolve_startup_gateway` (called
// from `main()` below) live in `gateway_switch.rs` — split out purely to
// keep this file under this project's 800-line convention. Rust allows an
// inherent `impl` to be split across files within the same crate, so no
// signature/call-site changes were needed anywhere: `screens::
// gateway_picker`'s `this.switch_to_local(cx)` / `this.begin_manual_
// connect(cx)` and `main()`'s `resolve_startup_gateway()` call below both
// keep resolving exactly as before.

impl Render for RootView {
    fn render(&mut self, _window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        // `self` reborrows as `&RootView` here (implicit `&mut T -> &T`
        // reborrow at the call site) — the screens only need to READ state
        // to render; mutation happens later, inside the `cx.listener`
        // closures they attach to clickable rows, which receive their own
        // fresh `&mut RootView` from the entity system when actually
        // invoked. All three screen `render` fns return the same concrete
        // `gpui::Div` type so the match arms unify without needing a boxed
        // `AnyElement`.
        let screen = match self.screen {
            Screen::Language => screens::language_picker::render(self, cx),
            Screen::Login => screens::login::render(self, cx),
            Screen::Shell => screens::shell::render(self, cx),
        };
        // S3: `.font(...)` applies at this single common ancestor of every
        // screen so the bundled font stack (`theme::app_font()`, see that
        // fn's doc comment) cascades to all text below — one call site
        // instead of repeating it in every `screens::*::render` fn.
        gpui::div().size_full().font(theme::app_font()).child(screen)
    }
}

fn main() {
    eprintln!("[main] starting duduclaw-native-gui S2");

    // WP-C-M2: resolve + seed the gateway target BEFORE anything else in
    // this crate makes a network call — `api::init_gateway_base_url` must
    // run ahead of `ws_status::spawn()`'s very first `TryLocalSession`
    // dispatch below, since that command reads the base URL dynamically
    // (see `api.rs`'s `GATEWAY_BASE` doc comment).
    let (initial_gateway_url, sidecar_manager) = gateway_switch::resolve_startup_gateway();
    api::init_gateway_base_url(initial_gateway_url);

    // Spawn the background session manager (HTTP login/local-session +
    // auto-reconnecting authenticated WS) before opening the window, and
    // fire the boot-time local-session probe immediately — its result
    // (arriving async, polled below) decides whether the user ever sees
    // the login form at all (task item 3: "啟動時先背景試 local session，成功
    // 直接進殼（跳過登入）").
    let (session_tx, session_rx) = ws_status::spawn();
    let _ = session_tx.send(SessionCommand::TryLocalSession);

    // S4: the dedicated chat socket manager — its own background thread/
    // runtime, independent of the session manager above (see `chat_ws.rs`'s
    // module doc comment for why separate, not shared).
    let (chat_tx, chat_rx) = chat_ws::spawn();

    // Locale persistence (task item 4): a resolvable saved locale skips
    // straight to the login screen; anything else (first launch, unreadable
    // file, unrecognized code) falls back to the language picker exactly as
    // Phase 1a always did. `config::load_locale` is fail-open by
    // construction — see its doc comment — so this can never block startup.
    let (initial_locale, initial_screen) = match config::load_locale() {
        Some(locale) => (locale, Screen::Login),
        None => (Locale::default(), Screen::Language),
    };
    eprintln!(
        "[main] initial locale={initial_locale:?} screen={initial_screen:?} \
         (persisted locale {})",
        if initial_screen == Screen::Login { "found" } else { "not found" }
    );

    eprintln!("[main] calling application().run(...)");
    application().run(move |cx: &mut App| {
        // S3: register the bundled font stack BEFORE opening the window —
        // any text laid out before `add_fonts` returns would resolve
        // against gpui's `.SystemUIFont` default and never re-flow onto the
        // bundled faces (there's no reactive re-layout-on-font-load here).
        //
        // Fail-open per this crate's established convention (`config::
        // load_locale`'s doc comment): a font-loading failure must not
        // block the window from opening at all — text simply falls back to
        // gpui's system-font default for this run, logged loudly to stderr
        // rather than silently swallowed or panicking.
        //
        // ICON-1 (2026-08-22): the two `include_bytes!` calls that used to
        // sit inline here now live next to `theme::app_font()` (the
        // function naming the very families these files provide) as
        // `theme::bundled_font_bytes()`, so `duduclaw-shell` — a second
        // gpui binary that the appliance launches directly, bypassing this
        // `main.rs` entirely — can register the identical stack without a
        // duplicated copy of a 12.8 MB TTF. Byte-for-byte the same faces in
        // the same order as before; only the call site moved.
        match cx.text_system().add_fonts(theme::bundled_font_bytes()) {
            Ok(()) => eprintln!("[main] add_fonts ok: InterVariable + NotoSansTC-Variable loaded"),
            Err(e) => eprintln!("[main] add_fonts FAILED (falling back to system font): {e}"),
        }

        // WP-C-M2: release a sidecar THIS app spawned on quit (Cmd+Q / Dock
        // quit / the native menu's QuitApp action — every path funnels
        // through `cx.quit()`, which fires every `on_app_quit` callback
        // before the process actually exits). `SidecarManager::stop()` is a
        // safe no-op both for a gateway this app only attached to (never
        // spawned) and for one already stopped — "app 關閉時自己 spawn 的
        // gateway 一併收（非自己 spawn 的不動）" per the task brief.
        let sidecar_for_quit = sidecar_manager.clone();
        cx.on_app_quit(move |_cx| {
            let mgr = sidecar_for_quit.clone();
            async move {
                mgr.stop();
            }
        })
        .detach();

        // Debug-only boot override, NOT part of the normal user flow: lets a
        // headless verification run (this crate has no scriptable UI-click
        // automation available — no accessibility/CI driver wired up) land
        // directly on a specific Shell nav page instead of always starting
        // at Language/Login, so a real `RootView::render` pass over that
        // page's actual code path can be observed in stderr rather than
        // just asserted from reading the click-handler source. Unset by
        // default; `DUDUCLAW_NATIVE_GUI_DEBUG_PAGE=componentLibrary` (any
        // valid `nav.rs` id) is the only way to trigger it.
        //
        // S4a extension: two more forms reach the design gallery —
        // `DUDUCLAW_NATIVE_GUI_DEBUG_PAGE=designGallery` boots into the
        // gallery on its first prototype, and `=proto:p08` boots straight
        // into that one prototype (skipping a manual click through the
        // 13-row list) — the form the S4a live-verification pass actually
        // uses to exercise each of the 13 pages in turn.
        let debug_page: Option<&'static str> = std::env::var("DUDUCLAW_NATIVE_GUI_DEBUG_PAGE")
            .ok()
            .filter(|s| !s.is_empty())
            .map(|s| -> &'static str { Box::leak(s.into_boxed_str()) });
        let (debug_active_page, debug_active_prototype): (Option<&'static str>, Option<&'static str>) =
            match debug_page {
                None => (None, None),
                Some(raw) => match raw.strip_prefix("proto:") {
                    Some(proto_id) => (Some("designGallery"), Some(proto_id)),
                    None if raw == "designGallery" => (Some("designGallery"), None),
                    None => (Some(raw), None),
                },
            };
        if let Some(page) = debug_page {
            eprintln!(
                "[main] DUDUCLAW_NATIVE_GUI_DEBUG_PAGE set — booting straight into Shell/{} (prototype={:?})",
                debug_active_page.unwrap_or(page),
                debug_active_prototype,
            );
        }

        eprintln!("[main] inside App closure, opening window");
        let bounds = Bounds::centered(None, gpui::size(px(1440.0), px(960.0)), cx);
        let session_tx_for_view = session_tx.clone();
        let chat_tx_for_view = chat_tx.clone();
        let sidecar_for_view = sidecar_manager.clone();
        let window = cx
            .open_window(
                WindowOptions {
                    window_bounds: Some(WindowBounds::Windowed(bounds)),
                    ..Default::default()
                },
                |_window, cx| {
                    let email_field = TextField::new(cx, "admin@local", false, "admin@local");
                    let password_field = TextField::new(cx, "••••••••", true, "");
                    // WP-C-M2: the gateway-picker manual-entry field.
                    // Placeholder shows the shape a candidate URL should
                    // take, not a real default — unlike email/password
                    // there's no natural "current value" to pre-fill (the
                    // currently-active target is shown READ-ONLY as the
                    // "本機"/discovered-list rows, not echoed into the input
                    // the user types a NEW target into).
                    let gateway_manual_field = TextField::new(cx, "http://192.168.1.5:18789", false, "");
                    // S4: the chat composer entity is created here (needs
                    // `&mut App`, available at this point) and handed into
                    // `ChatState`; the subscription below is what turns its
                    // `ImeTextInputEvent::Submit` (Enter-to-send) into an
                    // actual `chat_ws::Command::Send`.
                    let chat_input =
                        ime_input::ImeTextInput::new(cx, i18n::t(initial_locale, "native.chat.inputPlaceholder"));
                    let chat_input_for_sub = chat_input.clone();
                    cx.new(|cx| {
                        cx.subscribe(
                            &chat_input_for_sub,
                            |this: &mut RootView, _emitter, event: &ime_input::ImeTextInputEvent, cx| {
                                let ime_input::ImeTextInputEvent::Submit(content) = event;
                                this.chat.submit(content.clone());
                                // S4b: this listener is global (one
                                // subscription on the one shared composer
                                // entity — `dashboard_cards.rs`'s prompt bar
                                // reuses the SAME entity, see that module's
                                // doc comment), so navigating to the chat
                                // page here covers Enter-to-submit from
                                // EITHER page: submitting from `home`
                                // switches into `newChat` to show the
                                // exchange landing; submitting from
                                // `newChat` itself is a no-op reassignment.
                                this.active_page = "newChat";
                                cx.notify();
                            },
                        )
                        .detach();
                        RootView {
                            screen: if debug_page.is_some() { Screen::Shell } else { initial_screen },
                            locale: initial_locale,
                            ws_state: WsConnState::Disconnected,
                            email_field,
                            password_field,
                            active_page: debug_active_page.unwrap_or("home"),
                            active_prototype: debug_active_prototype
                                .unwrap_or(screens::prototypes::PROTOTYPES[0].id),
                            sidebar_collapsed: false,
                            session_tx: session_tx_for_view,
                            jwt: None,
                            refresh_token: None,
                            login_loading: false,
                            login_error: None,
                            chat: screens::chat::ChatState::new(chat_input, chat_tx_for_view),
                            display_name: None,
                            user_id: None,
                            spike_t7: screens::spike_t7::SpikeT7State::default(),
                            sidecar: sidecar_for_view,
                            gateway_manual_field,
                            gateway_connecting: false,
                            gateway_connect_error: None,
                            app_updater: updater::UpdaterManager::new(),
                        }
                    })
                },
            )
            .expect("failed to open window");
        eprintln!("[main] window opened");

        // P0-2: macOS menu bar (App/View/Window/Help — see
        // `native_menu.rs`'s header comment for why this is a whole-module
        // `#[cfg(target_os = "macos")]` gate, not a partial one). Must come
        // after `open_window` — every menu action closure captures `window`
        // to reach `RootView` state, the same `WindowHandle::update` bridge
        // the poll loop below uses.
        native_menu::install(cx, window, initial_locale);

        // Same bridge pattern as Phase 0a's smoke test: poll the mpsc
        // channel from gpui's foreground executor and push updates into
        // the view. I/O stays on the background thread/executor; only
        // `Entity`/`Window` updates happen on the foreground executor,
        // never a direct cross-thread mutation.
        cx.spawn(async move |cx| loop {
            let mut session_dead = false;
            let mut chat_dead = false;
            match session_rx.try_recv() {
                Ok(event) => {
                    let _ = window.update(cx, |view, _window, cx| {
                        view.handle_session_event(event);
                        cx.notify();
                    });
                }
                Err(mpsc::TryRecvError::Empty) => {}
                Err(mpsc::TryRecvError::Disconnected) => session_dead = true,
            }
            // S4: drained in the same poll tick as the session channel —
            // one background-thread bridge loop for both managers, rather
            // than a second `cx.spawn` (they're independent enough not to
            // NEED separate loops, and one loop is simpler to reason about
            // than two racing against the same `window` handle).
            match chat_rx.try_recv() {
                Ok(event) => {
                    let _ = window.update(cx, |view, _window, cx| {
                        view.handle_chat_event(event);
                        cx.notify();
                    });
                }
                Err(mpsc::TryRecvError::Empty) => {}
                Err(mpsc::TryRecvError::Disconnected) => chat_dead = true,
            }
            // WP-NG-debt: the dashboard's `maybe_fetch` used to be driven from
            // here (it needed a `&mut RootView` field this poll loop could
            // reach, back before `DashboardState` became a `gpui::Global` —
            // see that type's own doc comment). Now that its state lives
            // behind `Global`, it's called from `dashboard::render` itself,
            // same as every other S4b page's own `maybe_fetch*` — no `&mut
            // RootView` needed, so no poll-loop entry needed either.

            // WP-C-M2: the gateway-picker page's "本機" card reads `state.
            // sidecar.status()`/`.port()` directly (a cheap synchronous
            // Mutex/Atomic read, no channel needed — see `sidecar.rs`'s
            // `SidecarManager`) rather than through an event channel like
            // the session/chat managers above. That means nothing else in
            // this loop naturally triggers a re-render while the sidecar
            // transitions `Starting` -> `Running`/`Error` in the
            // background, so this page gets its own periodic `cx.notify()`
            // — scoped to ONLY fire while that page is actually visible, to
            // avoid needless re-render churn on every other page.
            let _ = window.update(cx, |view, _window, cx| {
                if view.active_page == "gatewayPicker" {
                    cx.notify();
                }
                // WP-C-M3: same reasoning as the `gatewayPicker` case just
                // above — `app_updater`'s status transitions (Checking ->
                // Available -> Downloading -> Installing -> ReadyToRestart)
                // happen on a background thread with no event channel back
                // into this loop, so the About page needs its own periodic
                // nudge to actually see them while it's the visible page.
                if view.active_page == "about" {
                    cx.notify();
                }
            });

            if session_dead && chat_dead {
                break;
            }
            cx.background_executor()
                .timer(Duration::from_millis(100))
                .await;
        })
        .detach();

        cx.activate(true);
    });
}
