//! Channel-level user access control: allowlist / blocklist / pairing codes.
//!
//! Backs the `/pair` chat command and the central per-user access gate in
//! `channel_reply`. Configuration lives in the `channel_settings` store
//! (global scope, per channel type): `allowed_users`, `blocked_users`,
//! `require_pairing`. Pairing codes are generated by the operator via the
//! `pairing_generate` MCP tool and verified in-channel with `/pair <code>`.
//!
//! ## Cross-process state
//!
//! Code generation happens in the MCP server process while verification
//! happens in the gateway process, so all state (approved subjects + pending
//! codes) lives in one JSON file (`~/.duduclaw/access_control.json`) that is
//! reloaded before every operation and rewritten atomically under an advisory
//! file lock (coding convention #3). Pending codes are stored as SHA-256
//! digests — the plaintext code exists only in the generate response.
//!
//! Slimmed 2026-07-07: the original (never-wired) version also carried tool
//! approvals, session scoping, and an emergency-stop state machine — all of
//! which duplicate live modules (`approval.rs`, `safety_word` failsafe) and
//! were dropped.

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::Arc;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use tokio::sync::RwLock;
use tracing::{info, warn};

/// Result of an access check.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AccessDecision {
    /// User is allowed to interact.
    Allowed,
    /// User is explicitly blocked — silently ignore.
    Blocked,
    /// User must present a pairing code first.
    RequirePairing,
}

/// A pending pairing code (persisted; code stored as SHA-256 hex digest).
///
/// Two counters (a bug in the never-compiled original used one, which froze
/// at the per-code lock and made both the 15-attempt generation cap
/// unreachable and every regenerated code born-locked):
/// - `failed_attempts`: failures against THIS code — 5 locks the code.
/// - `cumulative_failures`: failures across ALL codes for this subject —
///   15 blocks further code generation (anti brute-force-via-regeneration).
#[derive(Debug, Clone, Serialize, Deserialize)]
struct PendingCode {
    code_sha256: String,
    expires_at: DateTime<Utc>,
    failed_attempts: u32,
    #[serde(default)]
    cumulative_failures: u32,
}

/// On-disk state shared between the gateway and the MCP server process.
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
struct PersistState {
    /// Approved subjects (user ids or session ids).
    approved: Vec<String>,
    /// Pending pairing codes keyed by subject.
    pending: HashMap<String, PendingCode>,
}

/// Constant-time string comparison to prevent timing attacks.
fn constant_time_eq_str(a: &str, b: &str) -> bool {
    if a.len() != b.len() {
        return false;
    }
    a.bytes().zip(b.bytes()).fold(0u8, |acc, (x, y)| acc | (x ^ y)) == 0
}

fn sha256_hex(input: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(input.as_bytes());
    hex::encode(hasher.finalize())
}

/// Manages user-level access control and pairing.
pub struct AccessController {
    /// In-memory state; authoritative copy is the persist file when set.
    state: Arc<RwLock<PersistState>>,
    /// Path to the shared state file (None = in-memory only, for tests).
    persist_path: Option<PathBuf>,
}

impl AccessController {
    pub fn new() -> Self {
        Self {
            state: Arc::new(RwLock::new(PersistState::default())),
            persist_path: None,
        }
    }

    /// Create an AccessController backed by a shared state file.
    pub fn with_persistence(persist_path: PathBuf) -> Self {
        Self {
            state: Arc::new(RwLock::new(load_state(&persist_path))),
            persist_path: Some(persist_path),
        }
    }

    /// Reload state from disk (cross-process freshness). No-op without a path.
    async fn reload(&self) {
        if let Some(path) = &self.persist_path {
            let fresh = load_state(path);
            *self.state.write().await = fresh;
        }
    }

    /// Persist the current state to disk atomically under a file lock.
    async fn save(&self) {
        if let Some(path) = &self.persist_path {
            let snapshot = self.state.read().await.clone();
            let path = path.clone();
            let res = duduclaw_core::with_file_lock(&path, || {
                let json = serde_json::to_string_pretty(&snapshot)
                    .map_err(|e| std::io::Error::other(e.to_string()))?;
                let tmp = path.with_extension("json.tmp");
                std::fs::write(&tmp, json)?;
                std::fs::rename(&tmp, &path)
            });
            if let Err(e) = res {
                warn!(%e, "access_control state persist failed");
            }
        }
    }

    /// Check whether a subject is allowed to interact with the agent.
    pub async fn check_access(
        &self,
        user_id: &str,
        allowed_users: Option<&[String]>,
        blocked_users: &[String],
        require_pairing: bool,
    ) -> AccessDecision {
        // 1. Blocked users are always denied
        if blocked_users.iter().any(|b| b == user_id) {
            return AccessDecision::Blocked;
        }

        self.reload().await;
        let state = self.state.read().await;
        let runtime_approved = state.approved.iter().any(|a| a == user_id);

        // 2. If allowlist exists, check it (plus runtime-approved users)
        if let Some(allowed) = allowed_users {
            if allowed.iter().any(|a| a == user_id) || runtime_approved {
                return AccessDecision::Allowed;
            }
            // Not in allowlist → require pairing or block
            if require_pairing {
                return AccessDecision::RequirePairing;
            }
            return AccessDecision::Blocked;
        }

        // 3. No allowlist — check require_pairing
        if require_pairing {
            if runtime_approved {
                return AccessDecision::Allowed;
            }
            return AccessDecision::RequirePairing;
        }

        // 4. Open access
        AccessDecision::Allowed
    }

    /// Check access for both a user id and its session id — a pairing may have
    /// approved either (the central gate verifies `/pair` per-user; the
    /// chat_commands path verifies per-session). Blocked on either subject
    /// wins; then Allowed; then pairing.
    pub async fn check_access_dual(
        &self,
        user_id: &str,
        session_id: &str,
        allowed_users: Option<&[String]>,
        blocked_users: &[String],
        require_pairing: bool,
    ) -> AccessDecision {
        let by_user = self
            .check_access(user_id, allowed_users, blocked_users, require_pairing)
            .await;
        if by_user == AccessDecision::Blocked {
            return AccessDecision::Blocked;
        }
        let by_session = self
            .check_access(session_id, allowed_users, blocked_users, require_pairing)
            .await;
        if by_session == AccessDecision::Blocked {
            return AccessDecision::Blocked;
        }
        if by_user == AccessDecision::Allowed || by_session == AccessDecision::Allowed {
            return AccessDecision::Allowed;
        }
        AccessDecision::RequirePairing
    }

    /// Generate a 6-digit pairing code for a subject (valid for 5 minutes).
    ///
    /// Returns `None` if the cumulative failed attempt count across all
    /// generated codes has reached the hard limit of 15, preventing
    /// brute-force via repeated regeneration (R4-H1).
    pub async fn generate_pairing_code(&self, user_id: &str) -> Option<String> {
        self.reload().await;
        let code = {
            let mut state = self.state.write().await;

            // Carry the cumulative failure count across regenerations.
            let prev_cumulative = state
                .pending
                .get(user_id)
                .map(|p| p.cumulative_failures)
                .unwrap_or(0);

            // Hard limit: 15 total failed attempts across all generated codes
            if prev_cumulative >= 15 {
                warn!(user_id, "Pairing code generation blocked — too many cumulative attempts");
                return None;
            }

            // Use UUID-based entropy to avoid adding the `rand` crate
            let uuid = uuid::Uuid::new_v4();
            let num = uuid.as_u128() % 1_000_000;
            let code = format!("{num:06}");

            state.pending.insert(
                user_id.to_string(),
                PendingCode {
                    code_sha256: sha256_hex(&code),
                    expires_at: Utc::now() + chrono::Duration::minutes(5),
                    failed_attempts: 0, // fresh code, fresh per-code lock
                    cumulative_failures: prev_cumulative, // carried across codes
                },
            );
            code
        };
        self.save().await;

        info!(user_id, "Pairing code generated (expires in 5 min)");
        Some(code)
    }

    /// Verify a pairing code. On success, adds the subject to the approved
    /// list. No-op (false) when no code is pending for the subject — safe to
    /// probe multiple subjects for one `/pair` attempt.
    pub async fn verify_pairing_code(&self, user_id: &str, code: &str) -> bool {
        self.reload().await;
        let verified = {
            let mut state = self.state.write().await;
            let matches = match state.pending.get(user_id) {
                None => return false,
                Some(p) if p.failed_attempts >= 5 => {
                    warn!(user_id, "Pairing code locked — too many failed attempts");
                    return false;
                }
                Some(p) => {
                    constant_time_eq_str(&p.code_sha256, &sha256_hex(code))
                        && Utc::now() < p.expires_at
                }
            };
            if matches {
                state.pending.remove(user_id);
                if !state.approved.iter().any(|u| u == user_id) {
                    state.approved.push(user_id.to_string());
                }
                true
            } else {
                if let Some(p) = state.pending.get_mut(user_id) {
                    p.failed_attempts += 1;
                    p.cumulative_failures += 1;
                    warn!(
                        user_id,
                        attempts = p.failed_attempts,
                        cumulative = p.cumulative_failures,
                        "Pairing code verification failed"
                    );
                }
                false
            }
        };
        // Persist both outcomes: success moves the subject to approved;
        // failure must record the incremented attempt counter, or a
        // cross-process attacker gets a fresh 5 attempts per request.
        self.save().await;
        if verified {
            info!(user_id, "Pairing verified — user approved");
        }
        verified
    }

    /// Get the list of approved subjects.
    pub async fn runtime_approved_users(&self) -> Vec<String> {
        self.reload().await;
        self.state.read().await.approved.clone()
    }

    /// Manually approve a subject (from Dashboard / MCP).
    pub async fn approve_user(&self, user_id: &str) {
        self.reload().await;
        {
            let mut state = self.state.write().await;
            if state.approved.iter().any(|u| u == user_id) {
                return;
            }
            state.approved.push(user_id.to_string());
        }
        self.save().await;
        info!(user_id, "User manually approved");
    }

    /// Remove a subject from the approved list.
    pub async fn revoke_user(&self, user_id: &str) {
        self.reload().await;
        {
            let mut state = self.state.write().await;
            state.approved.retain(|u| u != user_id);
        }
        self.save().await;
        info!(user_id, "User revoked");
    }
}

impl Default for AccessController {
    fn default() -> Self {
        Self::new()
    }
}

/// Load state from disk. Accepts the current `PersistState` format and the
/// legacy plain `Vec<String>` approved-list format. Missing/corrupt file ⇒
/// empty state (open by default; the settings store gates enforcement).
fn load_state(path: &std::path::Path) -> PersistState {
    let Ok(data) = std::fs::read_to_string(path) else {
        return PersistState::default();
    };
    if let Ok(state) = serde_json::from_str::<PersistState>(&data) {
        return state;
    }
    if let Ok(approved) = serde_json::from_str::<Vec<String>>(&data) {
        return PersistState { approved, pending: HashMap::new() };
    }
    warn!(?path, "access_control state file is corrupt — starting empty");
    PersistState::default()
}

// ── Tests ───────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_open_access() {
        let ctrl = AccessController::new();
        assert_eq!(
            ctrl.check_access("user1", None, &[], false).await,
            AccessDecision::Allowed
        );
    }

    #[tokio::test]
    async fn test_blocked_user() {
        let ctrl = AccessController::new();
        let blocked = vec!["bad_user".to_string()];
        assert_eq!(
            ctrl.check_access("bad_user", None, &blocked, false).await,
            AccessDecision::Blocked
        );
    }

    #[tokio::test]
    async fn test_blocked_overrides_allowed() {
        let ctrl = AccessController::new();
        let allowed = vec!["user1".to_string()];
        let blocked = vec!["user1".to_string()];
        assert_eq!(
            ctrl.check_access("user1", Some(&allowed), &blocked, false).await,
            AccessDecision::Blocked
        );
    }

    #[tokio::test]
    async fn test_allowlist_denies_unknown() {
        let ctrl = AccessController::new();
        let allowed = vec!["user1".to_string()];
        assert_eq!(
            ctrl.check_access("user2", Some(&allowed), &[], false).await,
            AccessDecision::Blocked
        );
    }

    #[tokio::test]
    async fn test_require_pairing() {
        let ctrl = AccessController::new();
        assert_eq!(
            ctrl.check_access("user1", None, &[], true).await,
            AccessDecision::RequirePairing
        );
    }

    #[tokio::test]
    async fn test_pairing_flow() {
        let ctrl = AccessController::new();

        // Generate code
        let code = ctrl.generate_pairing_code("user1").await.expect("code should be generated");
        assert_eq!(code.len(), 6);

        // Verify with wrong code fails
        assert!(!ctrl.verify_pairing_code("user1", "000000").await);

        // Re-generate (failed attempts carry over; only success consumes)
        let code = ctrl.generate_pairing_code("user1").await.expect("code should be generated");

        // Verify with correct code succeeds
        assert!(ctrl.verify_pairing_code("user1", &code).await);

        // After pairing, user is approved
        assert_eq!(
            ctrl.check_access("user1", None, &[], true).await,
            AccessDecision::Allowed
        );
    }

    #[tokio::test]
    async fn test_pairing_lockout_across_regenerations() {
        let ctrl = AccessController::new();

        // Exhaust 15 cumulative attempts across multiple code generations
        let mut total_attempts = 0u32;
        loop {
            let code_opt = ctrl.generate_pairing_code("attacker").await;
            if code_opt.is_none() {
                break;
            }
            // Fail this code (adds to cumulative count)
            ctrl.verify_pairing_code("attacker", "000000").await;
            total_attempts += 1;
            if total_attempts > 20 {
                panic!("Should have been blocked before 20 attempts");
            }
        }
        // Generation should have been blocked before exceeding 15 total attempts
        assert!(total_attempts <= 15);
    }

    #[tokio::test]
    async fn test_regenerated_code_is_usable_after_per_code_lock() {
        // 5 failures lock the CURRENT code, but a regenerated code must be
        // verifiable — otherwise a legitimate user who fat-fingers 5 times can
        // never pair again (the single-counter bug in the original dead code).
        let ctrl = AccessController::new();
        let _old = ctrl.generate_pairing_code("user1").await.unwrap();
        for _ in 0..5 {
            assert!(!ctrl.verify_pairing_code("user1", "000000").await);
        }
        // Old code is locked now; regenerate and verify successfully.
        let fresh = ctrl.generate_pairing_code("user1").await.expect("regeneration allowed under cumulative cap");
        assert!(ctrl.verify_pairing_code("user1", &fresh).await);
    }

    #[tokio::test]
    async fn test_verify_without_pending_code_is_noop() {
        let ctrl = AccessController::new();
        // Probing a subject that has no pending code must fail without side effects.
        assert!(!ctrl.verify_pairing_code("nobody", "123456").await);
        assert!(ctrl.runtime_approved_users().await.is_empty());
    }

    #[tokio::test]
    async fn test_dual_check_blocked_wins() {
        let ctrl = AccessController::new();
        let blocked = vec!["user1".to_string()];
        // user_id blocked but session approved → still Blocked.
        ctrl.approve_user("telegram:123").await;
        assert_eq!(
            ctrl.check_access_dual("user1", "telegram:123", None, &blocked, true).await,
            AccessDecision::Blocked
        );
    }

    #[tokio::test]
    async fn test_dual_check_session_approval_allows() {
        let ctrl = AccessController::new();
        ctrl.approve_user("slack:group:C1").await;
        assert_eq!(
            ctrl.check_access_dual("U999", "slack:group:C1", None, &[], true).await,
            AccessDecision::Allowed
        );
    }

    #[tokio::test]
    async fn test_persistence_roundtrip() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("access_control.json");
        {
            let ctrl = AccessController::with_persistence(path.clone());
            ctrl.approve_user("user-persist").await;
        }
        let ctrl2 = AccessController::with_persistence(path);
        assert!(ctrl2.runtime_approved_users().await.contains(&"user-persist".to_string()));
    }

    #[tokio::test]
    async fn test_cross_process_generate_then_verify() {
        // Simulates the real deployment: the MCP server process generates a
        // code, the gateway process (separate controller instance) verifies it.
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("access_control.json");

        let mcp_side = AccessController::with_persistence(path.clone());
        let code = mcp_side.generate_pairing_code("tg-777").await.expect("generated");

        let gateway_side = AccessController::with_persistence(path);
        assert!(gateway_side.verify_pairing_code("tg-777", &code).await);
        assert_eq!(
            gateway_side.check_access("tg-777", None, &[], true).await,
            AccessDecision::Allowed
        );
    }

    #[tokio::test]
    async fn test_legacy_plain_list_format_still_loads() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("access_control.json");
        std::fs::write(&path, r#"["legacy-user"]"#).unwrap();
        let ctrl = AccessController::with_persistence(path);
        assert_eq!(
            ctrl.check_access("legacy-user", None, &[], true).await,
            AccessDecision::Allowed
        );
    }

    #[tokio::test]
    async fn test_failed_attempts_persist_across_instances() {
        // Attempt counter must survive process boundaries, or an attacker gets
        // a fresh budget per request.
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("access_control.json");

        let a = AccessController::with_persistence(path.clone());
        let _code = a.generate_pairing_code("victim").await.unwrap();
        for _ in 0..5 {
            assert!(!a.verify_pairing_code("victim", "000000").await);
        }
        // A fresh instance (≈ new process) must see the lockout.
        let b = AccessController::with_persistence(path);
        assert!(!b.verify_pairing_code("victim", "000000").await);
    }
}
