//! SQLite-backed persistent store for the Distributor White-Label Portal.
//!
//! Two tables:
//!   - `distributors` — one row per reseller (name, contact, note, status).
//!   - `issued_licenses` — every OEM license this owner instance has signed for
//!     a distributor, with its machine binding, validity window, status, and
//!     the base64 license blob (so it can be re-copied without re-signing).
//!
//! `DistributorStats` is **computed** from the two tables, never stored.
//!
//! Mirrors [`crate::partner_store`]: rusqlite, per-call connection, WAL +
//! `busy_timeout`, `CREATE TABLE IF NOT EXISTS` on first open, owner-only file
//! permissions on unix (via `duduclaw_core::platform::set_owner_only`).
//!
//! Signing lives here too (`issue_signed_oem_license`) because it is the
//! distributor domain and needs to be a pure, unit-testable function that the
//! handler layer calls with the real issuer seed + the production verify key.

use std::path::{Path, PathBuf};

use base64::{engine::general_purpose::STANDARD as BASE64, Engine};
use chrono::Utc;
use rusqlite::{params, Connection, OptionalExtension};
use serde::{Deserialize, Serialize};

use duduclaw_license::{License, LicenseTier, PublicKeyRegistry};

// ── Data types ──────────────────────────────────────────────

/// A reseller row (what the owner UI reads).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DistributorProfile {
    pub id: String,
    pub name: String,
    pub contact: Option<String>,
    pub note: Option<String>,
    pub status: String,
    pub created_at: String,
    pub updated_at: String,
}

/// Insert payload for a distributor. `id` + timestamps are generated by the store.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DistributorInput {
    pub name: String,
    #[serde(default)]
    pub contact: Option<String>,
    #[serde(default)]
    pub note: Option<String>,
}

/// Partial-update payload for a distributor. Any `Some` field overwrites.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DistributorPatch {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub contact: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

/// One issued license row.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IssuedLicense {
    pub id: String,
    pub distributor_id: String,
    pub subscription_id: String,
    pub customer_id: String,
    pub tier: String,
    pub machine_fingerprint: String,
    pub issued_at: String,
    pub expires_at: String,
    pub status: String,
    pub revoked_at: Option<String>,
    /// The base64 license blob (compatible with `duduclaw license activate`).
    pub license_blob: String,
    /// RFC3339 timestamp of the last successful control-plane `refresh` for this
    /// license (P2). `None` until the distributor instance phones home at least
    /// once — the owner UI reads this as a per-key "still alive" signal.
    #[serde(default)]
    pub last_refresh_at: Option<String>,
}

/// Computed rollup across both tables.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct DistributorStats {
    pub total_distributors: u64,
    pub active_distributors: u64,
    pub total_licenses: u64,
    pub active_licenses: u64,
    pub revoked_licenses: u64,
}

// ── Store ───────────────────────────────────────────────────

/// Per-request opened SQLite store — same "open a fresh store per RPC" pattern
/// as [`crate::partner_store::PartnerStore`] (low-traffic admin surface).
pub struct DistributorStore {
    db_path: PathBuf,
}

impl DistributorStore {
    pub fn new(db_path: &Path) -> Self {
        if let Some(parent) = db_path.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        if let Ok(conn) = Connection::open(db_path) {
            let _ = Self::init_schema(&conn);
        }
        // Owner-only (0600 on unix; no-op on Windows) — license blobs live here.
        let _ = duduclaw_core::platform::set_owner_only(db_path);
        Self {
            db_path: db_path.to_path_buf(),
        }
    }

    fn open_conn(&self) -> Result<Connection, String> {
        let conn =
            Connection::open(&self.db_path).map_err(|e| format!("open distributor store: {e}"))?;
        conn.busy_timeout(std::time::Duration::from_secs(5))
            .map_err(|e| format!("busy_timeout: {e}"))?;
        Ok(conn)
    }

    fn init_schema(conn: &Connection) -> Result<(), String> {
        conn.execute_batch(
            "PRAGMA journal_mode=WAL;
             PRAGMA busy_timeout=5000;

             CREATE TABLE IF NOT EXISTS distributors (
                 id          TEXT PRIMARY KEY,
                 name        TEXT NOT NULL,
                 contact     TEXT,
                 note        TEXT,
                 status      TEXT NOT NULL DEFAULT 'active',
                 created_at  TEXT NOT NULL,
                 updated_at  TEXT NOT NULL
             );

             CREATE TABLE IF NOT EXISTS issued_licenses (
                 id                   TEXT PRIMARY KEY,
                 distributor_id       TEXT NOT NULL,
                 subscription_id      TEXT NOT NULL,
                 customer_id          TEXT NOT NULL,
                 tier                 TEXT NOT NULL,
                 machine_fingerprint  TEXT NOT NULL,
                 issued_at            TEXT NOT NULL,
                 expires_at           TEXT NOT NULL,
                 status               TEXT NOT NULL DEFAULT 'active',
                 revoked_at           TEXT,
                 license_blob         TEXT NOT NULL
             );

             CREATE INDEX IF NOT EXISTS idx_issued_licenses_distributor
                 ON issued_licenses(distributor_id);
             CREATE INDEX IF NOT EXISTS idx_issued_licenses_status
                 ON issued_licenses(status);",
        )
        .map_err(|e| format!("init distributor store schema: {e}"))?;
        Self::add_refresh_columns(conn)?;
        Ok(())
    }

    /// Idempotently add the P2 phone-home ledger columns to a pre-existing
    /// `issued_licenses` table. Guarded by a `PRAGMA table_info` existence check
    /// so re-running on every open is a no-op (same pattern as
    /// [`crate::task_store`]'s dispatch-column migration).
    fn add_refresh_columns(conn: &Connection) -> Result<(), String> {
        let existing: std::collections::HashSet<String> = {
            let mut stmt = conn
                .prepare("PRAGMA table_info(issued_licenses)")
                .map_err(|e| format!("pragma table_info: {e}"))?;
            stmt.query_map([], |r| r.get::<_, String>(1))
                .map_err(|e| format!("query table_info: {e}"))?
                .collect::<Result<std::collections::HashSet<_>, _>>()
                .map_err(|e| format!("collect table_info: {e}"))?
        };
        // Nullable column — no DEFAULT needed; existing rows read NULL.
        let migrations: &[(&str, &str)] = &[("last_refresh_at", "last_refresh_at TEXT")];
        for (col, ddl) in migrations {
            if !existing.contains(*col) {
                conn.execute(
                    &format!("ALTER TABLE issued_licenses ADD COLUMN {ddl}"),
                    [],
                )
                .map_err(|e| format!("add column {col}: {e}"))?;
            }
        }
        Ok(())
    }

    // ── Distributors ────────────────────────────────────────

    pub fn list_distributors(&self) -> Vec<DistributorProfile> {
        let conn = match self.open_conn() {
            Ok(c) => c,
            Err(_) => return Vec::new(),
        };
        let mut stmt = match conn.prepare(
            "SELECT id, name, contact, note, status, created_at, updated_at
             FROM distributors ORDER BY created_at DESC",
        ) {
            Ok(s) => s,
            Err(_) => return Vec::new(),
        };
        let rows = stmt.query_map([], row_to_distributor).ok();
        match rows {
            Some(iter) => iter.filter_map(Result::ok).collect(),
            None => Vec::new(),
        }
    }

    pub fn get_distributor(&self, id: &str) -> Option<DistributorProfile> {
        let conn = self.open_conn().ok()?;
        conn.query_row(
            "SELECT id, name, contact, note, status, created_at, updated_at
             FROM distributors WHERE id = ?1",
            params![id],
            row_to_distributor,
        )
        .optional()
        .ok()
        .flatten()
    }

    /// Insert a distributor. Returns the generated UUID.
    pub fn add_distributor(&self, input: &DistributorInput) -> Result<String, String> {
        if input.name.trim().is_empty() {
            return Err("經銷商名稱為必填".to_string());
        }
        let conn = self.open_conn()?;
        let id = uuid::Uuid::new_v4().to_string();
        let now = Utc::now().to_rfc3339();
        conn.execute(
            "INSERT INTO distributors
                (id, name, contact, note, status, created_at, updated_at)
             VALUES (?1, ?2, ?3, ?4, 'active', ?5, ?5)",
            params![
                id,
                input.name.trim(),
                input.contact.as_deref().map(str::trim),
                input.note.as_deref().map(str::trim),
                now,
            ],
        )
        .map_err(|e| format!("insert distributor: {e}"))?;
        Ok(id)
    }

    /// Patch only the `Some` fields of a distributor.
    pub fn update_distributor(&self, id: &str, patch: &DistributorPatch) -> Result<(), String> {
        let conn = self.open_conn()?;
        let mut sets: Vec<String> = Vec::new();
        let mut binds: Vec<Box<dyn rusqlite::types::ToSql>> = Vec::new();

        if let Some(v) = &patch.name {
            binds.push(Box::new(v.clone()));
            sets.push(format!("name = ?{}", binds.len()));
        }
        if let Some(v) = &patch.contact {
            binds.push(Box::new(v.clone()));
            sets.push(format!("contact = ?{}", binds.len()));
        }
        if let Some(v) = &patch.note {
            binds.push(Box::new(v.clone()));
            sets.push(format!("note = ?{}", binds.len()));
        }
        if let Some(v) = &patch.status {
            binds.push(Box::new(v.clone()));
            sets.push(format!("status = ?{}", binds.len()));
        }

        // Always bump updated_at.
        binds.push(Box::new(Utc::now().to_rfc3339()));
        sets.push(format!("updated_at = ?{}", binds.len()));

        binds.push(Box::new(id.to_string()));
        let sql = format!(
            "UPDATE distributors SET {} WHERE id = ?{}",
            sets.join(", "),
            binds.len()
        );
        let params_ref: Vec<&dyn rusqlite::types::ToSql> =
            binds.iter().map(|b| b.as_ref()).collect();
        let affected = conn
            .execute(&sql, params_ref.as_slice())
            .map_err(|e| format!("update distributor: {e}"))?;
        if affected == 0 {
            return Err(format!("找不到經銷商 '{id}'"));
        }
        Ok(())
    }

    /// Delete a distributor. Refuses when any of its licenses are still active
    /// (the caller must revoke them first — a distributor with live keys should
    /// not vanish from the books).
    pub fn delete_distributor(&self, id: &str) -> Result<(), String> {
        if self.count_active_licenses(id) > 0 {
            return Err("此經銷商仍有生效中的授權金鑰，請先撤銷後再移除".to_string());
        }
        let conn = self.open_conn()?;
        let affected = conn
            .execute("DELETE FROM distributors WHERE id = ?1", params![id])
            .map_err(|e| format!("delete distributor: {e}"))?;
        if affected == 0 {
            return Err(format!("找不到經銷商 '{id}'"));
        }
        Ok(())
    }

    // ── Issued licenses ─────────────────────────────────────

    pub fn count_active_licenses(&self, distributor_id: &str) -> i64 {
        let conn = match self.open_conn() {
            Ok(c) => c,
            Err(_) => return 0,
        };
        conn.query_row(
            "SELECT COUNT(*) FROM issued_licenses
             WHERE distributor_id = ?1 AND status = 'active'",
            params![distributor_id],
            |r| r.get(0),
        )
        .unwrap_or(0)
    }

    /// List issued licenses, newest first. Optionally scoped to a distributor.
    pub fn list_licenses(&self, distributor_id: Option<&str>) -> Vec<IssuedLicense> {
        let conn = match self.open_conn() {
            Ok(c) => c,
            Err(_) => return Vec::new(),
        };
        let (sql, binds): (String, Vec<String>) = match distributor_id {
            Some(d) => (
                "SELECT id, distributor_id, subscription_id, customer_id, tier,
                        machine_fingerprint, issued_at, expires_at, status,
                        revoked_at, license_blob, last_refresh_at
                 FROM issued_licenses WHERE distributor_id = ?1
                 ORDER BY issued_at DESC"
                    .to_string(),
                vec![d.to_string()],
            ),
            None => (
                "SELECT id, distributor_id, subscription_id, customer_id, tier,
                        machine_fingerprint, issued_at, expires_at, status,
                        revoked_at, license_blob, last_refresh_at
                 FROM issued_licenses ORDER BY issued_at DESC"
                    .to_string(),
                vec![],
            ),
        };
        let mut stmt = match conn.prepare(&sql) {
            Ok(s) => s,
            Err(_) => return Vec::new(),
        };
        let binds_ref: Vec<&dyn rusqlite::types::ToSql> = binds
            .iter()
            .map(|s| s as &dyn rusqlite::types::ToSql)
            .collect();
        let rows = stmt.query_map(binds_ref.as_slice(), row_to_license).ok();
        match rows {
            Some(iter) => iter.filter_map(Result::ok).collect(),
            None => Vec::new(),
        }
    }

    pub fn get_license(&self, license_id: &str) -> Option<IssuedLicense> {
        let conn = self.open_conn().ok()?;
        conn.query_row(
            "SELECT id, distributor_id, subscription_id, customer_id, tier,
                    machine_fingerprint, issued_at, expires_at, status,
                    revoked_at, license_blob, last_refresh_at
             FROM issued_licenses WHERE id = ?1",
            params![license_id],
            row_to_license,
        )
        .optional()
        .ok()
        .flatten()
    }

    /// Look up an issued license by its `subscription_id` (the phone-home key —
    /// the client only knows its subscription + fingerprint, not our row id).
    /// Mirrors [`Self::get_license`] but keyed on `subscription_id`.
    pub fn get_license_by_subscription_id(&self, subscription_id: &str) -> Option<IssuedLicense> {
        let conn = self.open_conn().ok()?;
        conn.query_row(
            "SELECT id, distributor_id, subscription_id, customer_id, tier,
                    machine_fingerprint, issued_at, expires_at, status,
                    revoked_at, license_blob, last_refresh_at
             FROM issued_licenses WHERE subscription_id = ?1",
            params![subscription_id],
            row_to_license,
        )
        .optional()
        .ok()
        .flatten()
    }

    /// Record a successful control-plane refresh (P2 phone-home) for a license,
    /// stamping `last_refresh_at = now`. Best-effort ledger update — never
    /// blocks the re-signed response. Returns `Err` only on a DB failure.
    pub fn touch_refresh(&self, license_id: &str) -> Result<(), String> {
        let conn = self.open_conn()?;
        let now = Utc::now().to_rfc3339();
        conn.execute(
            "UPDATE issued_licenses SET last_refresh_at = ?1 WHERE id = ?2",
            params![now, license_id],
        )
        .map_err(|e| format!("touch refresh: {e}"))?;
        Ok(())
    }

    /// Insert a fully-formed issued-license record (id supplied by the caller so
    /// the same id can be embedded in the signed subscription/customer fields).
    pub fn add_license(&self, rec: &IssuedLicense) -> Result<(), String> {
        let conn = self.open_conn()?;
        conn.execute(
            "INSERT INTO issued_licenses
                (id, distributor_id, subscription_id, customer_id, tier,
                 machine_fingerprint, issued_at, expires_at, status,
                 revoked_at, license_blob)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)",
            params![
                rec.id,
                rec.distributor_id,
                rec.subscription_id,
                rec.customer_id,
                rec.tier,
                rec.machine_fingerprint,
                rec.issued_at,
                rec.expires_at,
                rec.status,
                rec.revoked_at,
                rec.license_blob,
            ],
        )
        .map_err(|e| format!("insert issued license: {e}"))?;
        Ok(())
    }

    /// Replace an issued license's stored `license_blob` (P-License upgrade,
    /// plan §12.1). Used by `distributor.upgrade` after re-signing the same key
    /// with a new `max_agents`. Only the blob changes — the ledger's
    /// subscription / fingerprint / validity columns are unchanged (the re-sign
    /// preserves them). `NotFound` if the id is unknown.
    pub fn update_license_blob(&self, license_id: &str, new_blob: &str) -> Result<(), String> {
        let conn = self.open_conn()?;
        let affected = conn
            .execute(
                "UPDATE issued_licenses SET license_blob = ?1 WHERE id = ?2",
                params![new_blob, license_id],
            )
            .map_err(|e| format!("update license blob: {e}"))?;
        if affected == 0 {
            return Err(format!("找不到授權 '{license_id}'"));
        }
        Ok(())
    }

    /// Mark a license `revoked` locally. Returns the affected record's
    /// distributor id for audit. NOTE: local bookkeeping only — remote
    /// propagation is a CRL/control-plane operation (see design §3.4).
    pub fn revoke_license(&self, license_id: &str) -> Result<(), String> {
        let conn = self.open_conn()?;
        let now = Utc::now().to_rfc3339();
        let affected = conn
            .execute(
                "UPDATE issued_licenses
                 SET status = 'revoked', revoked_at = ?1
                 WHERE id = ?2 AND status != 'revoked'",
                params![now, license_id],
            )
            .map_err(|e| format!("revoke license: {e}"))?;
        if affected == 0 {
            return Err(format!(
                "找不到可撤銷的授權 '{license_id}'（可能已撤銷或不存在）"
            ));
        }
        Ok(())
    }

    // ── Stats (computed) ────────────────────────────────────

    pub fn compute_stats(&self) -> DistributorStats {
        let conn = match self.open_conn() {
            Ok(c) => c,
            Err(_) => {
                return DistributorStats {
                    total_distributors: 0,
                    active_distributors: 0,
                    total_licenses: 0,
                    active_licenses: 0,
                    revoked_licenses: 0,
                };
            }
        };
        let count = |sql: &str| -> i64 { conn.query_row(sql, [], |r| r.get(0)).unwrap_or(0) };
        let total_distributors = count("SELECT COUNT(*) FROM distributors");
        let active_distributors =
            count("SELECT COUNT(*) FROM distributors WHERE status = 'active'");
        let total_licenses = count("SELECT COUNT(*) FROM issued_licenses");
        let active_licenses = count("SELECT COUNT(*) FROM issued_licenses WHERE status = 'active'");
        let revoked_licenses =
            count("SELECT COUNT(*) FROM issued_licenses WHERE status = 'revoked'");

        DistributorStats {
            total_distributors: total_distributors.max(0) as u64,
            active_distributors: active_distributors.max(0) as u64,
            total_licenses: total_licenses.max(0) as u64,
            active_licenses: active_licenses.max(0) as u64,
            revoked_licenses: revoked_licenses.max(0) as u64,
        }
    }
}

fn row_to_distributor(row: &rusqlite::Row) -> rusqlite::Result<DistributorProfile> {
    Ok(DistributorProfile {
        id: row.get(0)?,
        name: row.get(1)?,
        contact: row.get(2)?,
        note: row.get(3)?,
        status: row.get(4)?,
        created_at: row.get(5)?,
        updated_at: row.get(6)?,
    })
}

fn row_to_license(row: &rusqlite::Row) -> rusqlite::Result<IssuedLicense> {
    Ok(IssuedLicense {
        id: row.get(0)?,
        distributor_id: row.get(1)?,
        subscription_id: row.get(2)?,
        customer_id: row.get(3)?,
        tier: row.get(4)?,
        machine_fingerprint: row.get(5)?,
        issued_at: row.get(6)?,
        expires_at: row.get(7)?,
        status: row.get(8)?,
        revoked_at: row.get(9)?,
        license_blob: row.get(10)?,
        last_refresh_at: row.get(11)?,
    })
}

// ── Signing (pure, testable) ────────────────────────────────

/// Read the issuer signing seed from `path`. Same on-disk format as
/// `tools/license-keygen` produces: base64 of the 32-byte Ed25519 secret seed,
/// one line, optionally trailing whitespace.
///
/// The error messages deliberately NEVER echo the file contents — a leaked key
/// must not end up in a dashboard response or a log line.
pub fn load_issuer_signing_seed(path: &Path) -> Result<[u8; 32], String> {
    let content = std::fs::read_to_string(path)
        .map_err(|_| format!("無法讀取簽發金鑰檔案：{}", path.display()))?;
    let decoded = BASE64
        .decode(content.trim())
        .map_err(|_| "簽發金鑰格式錯誤（預期 base64 編碼的 32-byte Ed25519 私鑰）".to_string())?;
    let seed: [u8; 32] = decoded
        .try_into()
        .map_err(|_| "簽發金鑰長度錯誤（必須為 32 bytes）".to_string())?;
    Ok(seed)
}

/// Sign an OEM (`tier=Oem`) license with `signing_seed`, then **self-verify** it
/// against `verify_registry` before returning. The self-verify is the
/// "先驗證再套用" guard: if the issuer private key does not pair with the
/// trusted public key (`public_key_id` = `key_id`), no blob is produced.
///
/// Returns `(license, base64_blob)`. The blob is `base64(JSON(license))`, which
/// `duduclaw license activate` / `parse_license_input` decodes directly.
///
/// Pure and side-effect-free (no disk, no audit) so the sign→verify round-trip
/// is unit-testable with a throwaway keypair.
#[allow(clippy::too_many_arguments)]
pub fn issue_signed_oem_license(
    signing_seed: &[u8; 32],
    verify_registry: &PublicKeyRegistry,
    key_id: &str,
    subscription_id: &str,
    customer_id: &str,
    machine_fingerprint: &str,
    expires_days: i64,
    control_url: Option<&str>,
    branding_editable: Option<Vec<String>>,
    max_agents: Option<u32>,
) -> Result<(License, String), String> {
    let mut license = License::new(
        subscription_id,
        customer_id,
        LicenseTier::Oem,
        machine_fingerprint,
        chrono::Duration::days(expires_days),
        key_id,
    );
    // §10.5: bake the owner-gateway URL into the key so the client phones home
    // without needing DUDUCLAW_CONTROL_URL. Not part of the signed payload.
    license.control_url = control_url.map(str::to_string);
    // WP8: the field-level white-label edit claim. `None` = no restriction (the
    // consumer resolves it to the full vendor set — a reseller token); `Some`
    // narrows the editable range (a customer token). It IS part of the signed
    // payload, so the claim cannot be widened locally.
    license.branding_editable = branding_editable;
    // P-License: the signed per-license agent-count quota. `None` = no override
    // (tier default applies); `Some(n)` = sell exactly N (`Some(0)` = unlimited).
    // It IS part of the signed payload, so the count cannot be raised locally.
    license.max_agents = max_agents;
    sign_and_self_verify(signing_seed, verify_registry, key_id, license)
}

/// Re-sign an already-issued OEM license for a phone-home `refresh` (P2).
///
/// Preserves every economically-meaningful field of the original record —
/// `issued_at`, `expires_at`, `subscription_id`, `customer_id`,
/// `machine_fingerprint`, and `tier=Oem` — and only advances
/// `last_phone_home` to now (which is part of the signed payload, so a fresh
/// signature is required). **Refresh never extends validity**: a lapsed key is
/// re-subscribed by re-issuing, not by refreshing. `public_key_id` is pinned to
/// `"v2"` (the current issuer key). Shares the sign + self-verify kernel with
/// [`issue_signed_oem_license`], so a mismatched issuer/verify pair fails closed
/// with no blob produced.
///
/// Pure and side-effect-free (no disk, no ledger write) — the caller persists
/// `last_refresh_at` via [`DistributorStore::touch_refresh`].
pub fn resign_license_for_refresh(
    signing_seed: &[u8; 32],
    verify_registry: &PublicKeyRegistry,
    rec: &IssuedLicense,
) -> Result<(License, String), String> {
    // `None` override ⇒ keep the previously-signed `max_agents` verbatim.
    resign_license_preserving(signing_seed, verify_registry, rec, None)
}

/// Re-sign an already-issued OEM license with a **new** `max_agents` (P-License
/// upgrade / add-on, plan §12.1 gateway offline path).
///
/// Preserves every other economically-meaningful field — `subscription_id`,
/// `customer_id`, `machine_fingerprint`, `issued_at`, `expires_at`,
/// `control_url`, and the `branding_editable` claim — and only swaps the signed
/// agent-count quota. `new_max_agents`: `Some(n)` sells exactly N (`Some(0)` =
/// unlimited); `None` clears the override back to the tier default. Shares the
/// [`resign_license_preserving`] kernel + sign/self-verify guard with
/// [`resign_license_for_refresh`] (a mismatched issuer/verify pair fails closed).
///
/// The re-signed blob can be handed to the customer directly; the cloud/gateway
/// `refresh` re-sign reads the previous blob, so once
/// [`DistributorStore::update_license_blob`] stores it, subsequent phone-home
/// re-signs naturally carry the new count.
pub fn resign_license_with_max_agents(
    signing_seed: &[u8; 32],
    verify_registry: &PublicKeyRegistry,
    rec: &IssuedLicense,
    new_max_agents: Option<u32>,
) -> Result<(License, String), String> {
    resign_license_preserving(signing_seed, verify_registry, rec, Some(new_max_agents))
}

/// Shared re-sign kernel for refresh + upgrade. Rebuilds the signed License from
/// the ledger record + previous blob, applies an optional `max_agents` override,
/// advances `last_phone_home`, pins `public_key_id = "v2"`, then signs +
/// self-verifies.
///
/// `max_agents_override`: `None` = keep the previous blob's `max_agents`;
/// `Some(v)` = set it to `v` (where `v` is itself `Option<u32>`, `Some(0)` =
/// unlimited, `None` = tier default).
fn resign_license_preserving(
    signing_seed: &[u8; 32],
    verify_registry: &PublicKeyRegistry,
    rec: &IssuedLicense,
    max_agents_override: Option<Option<u32>>,
) -> Result<(License, String), String> {
    use chrono::{DateTime, Utc};

    let issued_at = DateTime::parse_from_rfc3339(&rec.issued_at)
        .map_err(|e| format!("parse issued_at: {e}"))?
        .with_timezone(&Utc);
    let expires_at = DateTime::parse_from_rfc3339(&rec.expires_at)
        .map_err(|e| format!("parse expires_at: {e}"))?
        .with_timezone(&Utc);

    // §10.5 / WP8: preserve the original self-carried `control_url` AND the
    // signed `branding_editable` claim so a re-signed key keeps phoning home to
    // the same owner gateway and keeps the exact same field-level edit range. A
    // re-sign must never widen the claim (that would let a customer escalate to
    // full vendor editing by triggering a re-sign), so we copy it verbatim from
    // the previously-issued blob. The ledger has no dedicated columns for these,
    // but the stored `license_blob` is the signed License JSON. A blob that does
    // not decode (legacy "blob" placeholders in tests) yields None for both.
    let prev = BASE64
        .decode(rec.license_blob.trim())
        .ok()
        .and_then(|bytes| serde_json::from_slice::<License>(&bytes).ok());
    let control_url = prev.as_ref().and_then(|l| l.control_url.clone());
    let branding_editable = prev.as_ref().and_then(|l| l.branding_editable.clone());
    // P-License: an upgrade sets `max_agents` explicitly; a refresh preserves the
    // signed quota verbatim (never widen or silently drop to the tier default).
    let max_agents = match max_agents_override {
        Some(v) => v,
        None => prev.as_ref().and_then(|l| l.max_agents),
    };

    let license = License {
        version: duduclaw_license::CURRENT_SCHEMA_VERSION,
        subscription_id: rec.subscription_id.clone(),
        customer_id: rec.customer_id.clone(),
        tier: LicenseTier::Oem,
        machine_fingerprint: rec.machine_fingerprint.clone(),
        issued_at,
        expires_at,
        last_phone_home: Utc::now(),
        public_key_id: "v2".to_string(),
        signature: Vec::new(),
        control_url,
        branding_editable,
        max_agents,
        // NFR marker survives refresh/upgrade — a re-signed test license must
        // never come back clean.
        nfr: prev.as_ref().is_some_and(|l| l.nfr),
    };
    sign_and_self_verify(signing_seed, verify_registry, "v2", license)
}

/// Whether `signing_seed` is a genuine, ecosystem-trusted issuer key — i.e. it
/// can mint licenses that verify against `verify_registry`'s trusted public
/// keys. **Non-forgeable** (WP8): a random 32-byte seed (e.g. a customer-admin
/// pointing `[distributor] issuer_key_path` at an attacker-controlled file)
/// derives a public key that is NOT in the trusted registry, so it fails. This
/// gates System-scope branding rights so mere config presence cannot escalate a
/// restricted customer token to full editing. Signs a throwaway probe license
/// and requires it to verify — proving the private seed pairs with a trusted
/// public key. No disk / audit side effects.
pub fn issuer_seed_is_trusted(
    signing_seed: &[u8; 32],
    verify_registry: &PublicKeyRegistry,
) -> bool {
    let probe = License::new(
        "issuer-probe",
        "issuer-probe",
        LicenseTier::Oem,
        "issuer-probe",
        chrono::Duration::days(1),
        "v2",
    );
    sign_and_self_verify(signing_seed, verify_registry, "v2", probe).is_ok()
}

/// Shared sign + self-verify + blob-encode kernel. Signs `license`'s canonical
/// payload with `signing_seed`, then self-verifies against `verify_registry`
/// (the "先驗證再套用" guard — no blob is produced if the issuer private key
/// does not pair with the trusted `key_id` public key). Returns
/// `(license, base64(JSON(license)))`.
fn sign_and_self_verify(
    signing_seed: &[u8; 32],
    verify_registry: &PublicKeyRegistry,
    key_id: &str,
    mut license: License,
) -> Result<(License, String), String> {
    use ed25519_dalek::{Signer, SigningKey};

    let payload = license
        .canonical_payload()
        .map_err(|e| format!("canonical payload: {e}"))?;
    let signing = SigningKey::from_bytes(signing_seed);
    license.signature = signing.sign(&payload).to_bytes().to_vec();

    // Self-verify: issuer seed must pair with the trusted verify key for this id.
    verify_registry
        .verify(&license)
        .map_err(|e| format!("簽發自驗失敗（issuer 私鑰與內建 {key_id} 公鑰不成對）：{e}"))?;

    let json = serde_json::to_string(&license).map_err(|e| format!("serialize license: {e}"))?;
    let blob = BASE64.encode(json.as_bytes());
    Ok((license, blob))
}

#[cfg(test)]
mod tests {
    use super::*;
    use ed25519_dalek::SigningKey;
    use rand::rngs::OsRng;
    use tempfile::tempdir;

    fn make_store() -> (tempfile::TempDir, DistributorStore) {
        let dir = tempdir().unwrap();
        let path = dir.path().join("distributor.db");
        (dir, DistributorStore::new(&path))
    }

    #[test]
    fn distributor_crud_roundtrip() {
        let (_dir, store) = make_store();
        let id = store
            .add_distributor(&DistributorInput {
                name: "北區經銷 Acme".into(),
                contact: Some("sales@acme.example".into()),
                note: None,
            })
            .unwrap();
        assert!(!id.is_empty());

        let all = store.list_distributors();
        assert_eq!(all.len(), 1);
        assert_eq!(all[0].name, "北區經銷 Acme");
        assert_eq!(all[0].status, "active");

        store
            .update_distributor(
                &id,
                &DistributorPatch {
                    status: Some("suspended".into()),
                    note: Some("暫停合作".into()),
                    ..Default::default()
                },
            )
            .unwrap();
        let got = store.get_distributor(&id).unwrap();
        assert_eq!(got.status, "suspended");
        assert_eq!(got.note.as_deref(), Some("暫停合作"));

        store.delete_distributor(&id).unwrap();
        assert!(store.list_distributors().is_empty());
    }

    #[test]
    fn delete_refused_while_active_license_exists() {
        let (_dir, store) = make_store();
        let did = store
            .add_distributor(&DistributorInput {
                name: "有金鑰的經銷".into(),
                contact: None,
                note: None,
            })
            .unwrap();
        store
            .add_license(&IssuedLicense {
                id: "lic-1".into(),
                distributor_id: did.clone(),
                subscription_id: "dist-x-1".into(),
                customer_id: "dist-x".into(),
                tier: "oem".into(),
                machine_fingerprint: "fp".into(),
                issued_at: Utc::now().to_rfc3339(),
                expires_at: Utc::now().to_rfc3339(),
                status: "active".into(),
                revoked_at: None,
                license_blob: "blob".into(),
                last_refresh_at: None,
            })
            .unwrap();

        assert!(store.delete_distributor(&did).is_err());
        // After revoking, delete succeeds.
        store.revoke_license("lic-1").unwrap();
        store.delete_distributor(&did).unwrap();
    }

    #[test]
    fn revoke_and_stats() {
        let (_dir, store) = make_store();
        let did = store
            .add_distributor(&DistributorInput {
                name: "D".into(),
                contact: None,
                note: None,
            })
            .unwrap();
        for i in 0..3 {
            store
                .add_license(&IssuedLicense {
                    id: format!("lic-{i}"),
                    distributor_id: did.clone(),
                    subscription_id: format!("dist-x-{i}"),
                    customer_id: "dist-x".into(),
                    tier: "oem".into(),
                    machine_fingerprint: "fp".into(),
                    issued_at: Utc::now().to_rfc3339(),
                    expires_at: Utc::now().to_rfc3339(),
                    status: "active".into(),
                    revoked_at: None,
                    license_blob: "blob".into(),
                    last_refresh_at: None,
                })
                .unwrap();
        }
        store.revoke_license("lic-0").unwrap();
        // Double revoke fails (already revoked).
        assert!(store.revoke_license("lic-0").is_err());

        let stats = store.compute_stats();
        assert_eq!(stats.total_distributors, 1);
        assert_eq!(stats.total_licenses, 3);
        assert_eq!(stats.active_licenses, 2);
        assert_eq!(stats.revoked_licenses, 1);
        assert_eq!(store.list_licenses(Some(&did)).len(), 3);
    }

    #[test]
    fn sign_and_self_verify_roundtrip() {
        // Generate a throwaway issuer keypair and trust its public half under "v2".
        let signing = SigningKey::generate(&mut OsRng);
        let seed: [u8; 32] = signing.to_bytes();
        let pubkey = signing.verifying_key().to_bytes().to_vec();
        let registry = PublicKeyRegistry::new().with_key("v2", pubkey);

        let fp = duduclaw_license::generate_fingerprint();
        let (license, blob) =
            issue_signed_oem_license(&seed, &registry, "v2", "dist-abc-001", "dist-abc", &fp, 365, None, None, None)
                .expect("sign+verify should succeed for a paired key");

        assert_eq!(license.tier, LicenseTier::Oem);
        assert_eq!(license.public_key_id, "v2");

        // Blob must round-trip through the CLI parse path: base64 → JSON → License.
        let decoded = BASE64.decode(blob.trim()).unwrap();
        let parsed: License = serde_json::from_slice(&decoded).unwrap();
        assert_eq!(parsed.subscription_id, "dist-abc-001");
        assert_eq!(parsed.machine_fingerprint, fp);
        // The parsed blob still verifies against the trusting registry.
        assert!(registry.verify(&parsed).is_ok());
    }

    #[test]
    fn branding_editable_claim_round_trips_through_signed_blob() {
        // WP8: issue with a restricted field-level claim; the signed blob must
        // carry it verbatim, survive verification, and still verify after parse.
        let signing = SigningKey::generate(&mut OsRng);
        let seed: [u8; 32] = signing.to_bytes();
        let registry =
            PublicKeyRegistry::new().with_key("v2", signing.verifying_key().to_bytes().to_vec());
        let fp = duduclaw_license::generate_fingerprint();

        let claim = vec!["logo_data_uri".to_string(), "accent_color".to_string()];
        let (license, blob) = issue_signed_oem_license(
            &seed,
            &registry,
            "v2",
            "dist-claim-1",
            "dist-claim",
            &fp,
            365,
            None,
            Some(claim.clone()),
            None,
        )
        .expect("issue with claim");
        assert_eq!(license.branding_editable.as_ref(), Some(&claim));

        let decoded = BASE64.decode(blob.trim()).unwrap();
        let parsed: License = serde_json::from_slice(&decoded).unwrap();
        assert_eq!(parsed.branding_editable.as_ref(), Some(&claim));
        assert!(registry.verify(&parsed).is_ok());
    }

    #[test]
    fn resign_preserves_branding_editable_claim() {
        // A refresh must NOT widen (or drop) the claim — a customer token stays a
        // customer token across phone-home re-signs.
        let signing = SigningKey::generate(&mut OsRng);
        let seed: [u8; 32] = signing.to_bytes();
        let registry =
            PublicKeyRegistry::new().with_key("v2", signing.verifying_key().to_bytes().to_vec());
        let fp = duduclaw_license::generate_fingerprint();

        let claim = vec!["logo_data_uri".to_string()];
        let (original, blob) = issue_signed_oem_license(
            &seed,
            &registry,
            "v2",
            "dist-c-1",
            "dist-c",
            &fp,
            365,
            None,
            Some(claim.clone()),
            None,
        )
        .expect("initial issue");

        let rec = IssuedLicense {
            id: "lic-c".into(),
            distributor_id: "d".into(),
            subscription_id: "dist-c-1".into(),
            customer_id: "dist-c".into(),
            tier: "oem".into(),
            machine_fingerprint: fp.clone(),
            issued_at: original.issued_at.to_rfc3339(),
            expires_at: original.expires_at.to_rfc3339(),
            status: "active".into(),
            revoked_at: None,
            license_blob: blob,
            last_refresh_at: None,
        };
        let (resigned, new_blob) =
            resign_license_for_refresh(&seed, &registry, &rec).expect("resign");
        assert_eq!(resigned.branding_editable.as_ref(), Some(&claim));
        let decoded = BASE64.decode(new_blob.trim()).unwrap();
        let parsed: License = serde_json::from_slice(&decoded).unwrap();
        assert_eq!(parsed.branding_editable.as_ref(), Some(&claim));
        assert!(registry.verify(&parsed).is_ok());
    }

    #[test]
    fn issue_and_resign_preserve_max_agents_quota() {
        // P-License: a "sell 5 agents" OEM key must (a) carry a verifiable signed
        // quota of 5, and (b) still be 5 after a phone-home refresh re-sign — the
        // quota must never silently drop back to the tier default.
        let signing = SigningKey::generate(&mut OsRng);
        let seed: [u8; 32] = signing.to_bytes();
        let registry =
            PublicKeyRegistry::new().with_key("v2", signing.verifying_key().to_bytes().to_vec());
        let fp = duduclaw_license::generate_fingerprint();

        let (original, blob) = issue_signed_oem_license(
            &seed,
            &registry,
            "v2",
            "dist-q-1",
            "dist-q",
            &fp,
            365,
            None,
            None,
            Some(5),
        )
        .expect("initial issue with quota");
        assert_eq!(original.max_agents, Some(5));
        assert!(registry.verify(&original).is_ok());

        let rec = IssuedLicense {
            id: "lic-q".into(),
            distributor_id: "d".into(),
            subscription_id: "dist-q-1".into(),
            customer_id: "dist-q".into(),
            tier: "oem".into(),
            machine_fingerprint: fp.clone(),
            issued_at: original.issued_at.to_rfc3339(),
            expires_at: original.expires_at.to_rfc3339(),
            status: "active".into(),
            revoked_at: None,
            license_blob: blob,
            last_refresh_at: None,
        };
        let (resigned, new_blob) =
            resign_license_for_refresh(&seed, &registry, &rec).expect("resign");
        assert_eq!(resigned.max_agents, Some(5), "quota preserved across refresh");
        let decoded = BASE64.decode(new_blob.trim()).unwrap();
        let parsed: License = serde_json::from_slice(&decoded).unwrap();
        assert_eq!(parsed.max_agents, Some(5));
        assert!(registry.verify(&parsed).is_ok());
    }

    #[test]
    fn upgrade_resigns_new_max_agents_and_refresh_carries_it() {
        // P-License upgrade: issue 5 → upgrade to 8 (new blob verifies + carries
        // 8) → a subsequent phone-home refresh must keep 8, not drop it.
        let signing = SigningKey::generate(&mut OsRng);
        let seed: [u8; 32] = signing.to_bytes();
        let registry =
            PublicKeyRegistry::new().with_key("v2", signing.verifying_key().to_bytes().to_vec());
        let fp = duduclaw_license::generate_fingerprint();

        let (original, blob) = issue_signed_oem_license(
            &seed, &registry, "v2", "dist-up-1", "dist-up", &fp, 365, None, None, Some(5),
        )
        .expect("initial issue with quota 5");
        assert_eq!(original.max_agents, Some(5));

        let rec = IssuedLicense {
            id: "lic-up".into(),
            distributor_id: "d".into(),
            subscription_id: "dist-up-1".into(),
            customer_id: "dist-up".into(),
            tier: "oem".into(),
            machine_fingerprint: fp.clone(),
            issued_at: original.issued_at.to_rfc3339(),
            expires_at: original.expires_at.to_rfc3339(),
            status: "active".into(),
            revoked_at: None,
            license_blob: blob,
            last_refresh_at: None,
        };

        // Upgrade 5 → 8. Identity + validity preserved, only the quota changes.
        let (upgraded, new_blob) =
            resign_license_with_max_agents(&seed, &registry, &rec, Some(8)).expect("upgrade");
        assert_eq!(upgraded.max_agents, Some(8), "new ceiling signed in");
        assert_eq!(upgraded.subscription_id, "dist-up-1");
        assert_eq!(upgraded.machine_fingerprint, fp);
        assert_eq!(upgraded.issued_at, original.issued_at, "validity untouched");
        assert_eq!(upgraded.expires_at, original.expires_at);
        // The upgraded blob verifies against the trusted key.
        let decoded = BASE64.decode(new_blob.trim()).unwrap();
        let parsed: License = serde_json::from_slice(&decoded).unwrap();
        assert_eq!(parsed.max_agents, Some(8));
        assert!(registry.verify(&parsed).is_ok());

        // Refresh re-sign reads the (now upgraded) blob → still 8.
        let rec_after = IssuedLicense {
            license_blob: new_blob,
            ..rec.clone()
        };
        let (refreshed, _) =
            resign_license_for_refresh(&seed, &registry, &rec_after).expect("refresh");
        assert_eq!(refreshed.max_agents, Some(8), "refresh keeps the upgraded quota");
    }

    #[test]
    fn update_license_blob_swaps_and_refresh_reads_new() {
        // Store-level: upgrade path persists the new blob; the row then re-signs
        // (refresh) off the upgraded blob.
        let signing = SigningKey::generate(&mut OsRng);
        let seed: [u8; 32] = signing.to_bytes();
        let registry =
            PublicKeyRegistry::new().with_key("v2", signing.verifying_key().to_bytes().to_vec());
        let fp = duduclaw_license::generate_fingerprint();
        let (_orig, blob) = issue_signed_oem_license(
            &seed, &registry, "v2", "dist-sb-1", "dist-sb", &fp, 365, None, None, Some(5),
        )
        .unwrap();

        let (_dir, store) = make_store();
        let did = store
            .add_distributor(&DistributorInput { name: "D".into(), contact: None, note: None })
            .unwrap();
        store
            .add_license(&IssuedLicense {
                id: "lic-sb".into(),
                distributor_id: did,
                subscription_id: "dist-sb-1".into(),
                customer_id: "dist-sb".into(),
                tier: "oem".into(),
                machine_fingerprint: fp.clone(),
                issued_at: _orig.issued_at.to_rfc3339(),
                expires_at: _orig.expires_at.to_rfc3339(),
                status: "active".into(),
                revoked_at: None,
                license_blob: blob,
                last_refresh_at: None,
            })
            .unwrap();

        // Upgrade to 8 and persist.
        let rec = store.get_license("lic-sb").unwrap();
        let (_up, new_blob) =
            resign_license_with_max_agents(&seed, &registry, &rec, Some(8)).unwrap();
        store.update_license_blob("lic-sb", &new_blob).unwrap();

        // The stored blob now carries 8.
        let after = store.get_license("lic-sb").unwrap();
        let decoded = BASE64.decode(after.license_blob.trim()).unwrap();
        let parsed: License = serde_json::from_slice(&decoded).unwrap();
        assert_eq!(parsed.max_agents, Some(8));

        // Unknown id → NotFound-style error.
        assert!(store.update_license_blob("nope", &new_blob).is_err());
    }

    #[test]
    fn sign_self_verify_fails_for_mismatched_pubkey() {
        // Sign with one key, trust a DIFFERENT key → self-verify must reject and
        // NOT return a blob (guards issuer-key ↔ baked-pubkey pairing).
        let signing = SigningKey::generate(&mut OsRng);
        let seed: [u8; 32] = signing.to_bytes();
        let other = SigningKey::generate(&mut OsRng);
        let registry =
            PublicKeyRegistry::new().with_key("v2", other.verifying_key().to_bytes().to_vec());

        let fp = duduclaw_license::generate_fingerprint();
        let res = issue_signed_oem_license(&seed, &registry, "v2", "dist-x-1", "dist-x", &fp, 365, None, None, None);
        assert!(
            res.is_err(),
            "mismatched issuer/verify key must fail self-verify"
        );
    }

    #[test]
    fn get_license_by_subscription_id_roundtrip() {
        let (_dir, store) = make_store();
        let did = store
            .add_distributor(&DistributorInput {
                name: "D".into(),
                contact: None,
                note: None,
            })
            .unwrap();
        store
            .add_license(&IssuedLicense {
                id: "lic-sub".into(),
                distributor_id: did,
                subscription_id: "dist-x-abc123".into(),
                customer_id: "dist-x".into(),
                tier: "oem".into(),
                machine_fingerprint: "fp".into(),
                issued_at: Utc::now().to_rfc3339(),
                expires_at: Utc::now().to_rfc3339(),
                status: "active".into(),
                revoked_at: None,
                license_blob: "blob".into(),
                last_refresh_at: None,
            })
            .unwrap();

        let found = store
            .get_license_by_subscription_id("dist-x-abc123")
            .expect("lookup by subscription id");
        assert_eq!(found.id, "lic-sub");
        assert!(found.last_refresh_at.is_none());
        // Unknown subscription → None (fail-closed at the handler layer).
        assert!(store.get_license_by_subscription_id("nope").is_none());
    }

    #[test]
    fn touch_refresh_stamps_last_refresh_at() {
        let (_dir, store) = make_store();
        let did = store
            .add_distributor(&DistributorInput {
                name: "D".into(),
                contact: None,
                note: None,
            })
            .unwrap();
        store
            .add_license(&IssuedLicense {
                id: "lic-tr".into(),
                distributor_id: did,
                subscription_id: "dist-x-tr".into(),
                customer_id: "dist-x".into(),
                tier: "oem".into(),
                machine_fingerprint: "fp".into(),
                issued_at: Utc::now().to_rfc3339(),
                expires_at: Utc::now().to_rfc3339(),
                status: "active".into(),
                revoked_at: None,
                license_blob: "blob".into(),
                last_refresh_at: None,
            })
            .unwrap();
        assert!(store.get_license("lic-tr").unwrap().last_refresh_at.is_none());
        store.touch_refresh("lic-tr").unwrap();
        assert!(store.get_license("lic-tr").unwrap().last_refresh_at.is_some());
    }

    #[test]
    fn resign_preserves_validity_only_updates_phone_home() {
        // Throwaway issuer keypair trusted under "v2".
        let signing = SigningKey::generate(&mut OsRng);
        let seed: [u8; 32] = signing.to_bytes();
        let registry = PublicKeyRegistry::new()
            .with_key("v2", signing.verifying_key().to_bytes().to_vec());

        let fp = duduclaw_license::generate_fingerprint();
        let (original, _blob) =
            issue_signed_oem_license(&seed, &registry, "v2", "dist-r-1", "dist-r", &fp, 365, None, None, None)
                .expect("initial issue");

        // Build the ledger record from the issued license (as the store would).
        let rec = IssuedLicense {
            id: "lic-r".into(),
            distributor_id: "d".into(),
            subscription_id: "dist-r-1".into(),
            customer_id: "dist-r".into(),
            tier: "oem".into(),
            machine_fingerprint: fp.clone(),
            issued_at: original.issued_at.to_rfc3339(),
            expires_at: original.expires_at.to_rfc3339(),
            status: "active".into(),
            revoked_at: None,
            license_blob: _blob,
            last_refresh_at: None,
        };

        let (resigned, blob) =
            resign_license_for_refresh(&seed, &registry, &rec).expect("resign");

        // Validity window + identity preserved to the second — NO extension.
        assert_eq!(resigned.issued_at, original.issued_at);
        assert_eq!(resigned.expires_at, original.expires_at);
        assert_eq!(resigned.subscription_id, "dist-r-1");
        assert_eq!(resigned.customer_id, "dist-r");
        assert_eq!(resigned.machine_fingerprint, fp);
        assert_eq!(resigned.tier, LicenseTier::Oem);
        assert_eq!(resigned.public_key_id, "v2");
        // last_phone_home advanced (>= original).
        assert!(resigned.last_phone_home >= original.last_phone_home);
        // Re-signed blob round-trips and re-verifies.
        let decoded = BASE64.decode(blob.trim()).unwrap();
        let parsed: License = serde_json::from_slice(&decoded).unwrap();
        assert!(registry.verify(&parsed).is_ok());
    }

    #[test]
    fn resign_fails_for_mismatched_pubkey() {
        let signing = SigningKey::generate(&mut OsRng);
        let seed: [u8; 32] = signing.to_bytes();
        let other = SigningKey::generate(&mut OsRng);
        let registry = PublicKeyRegistry::new()
            .with_key("v2", other.verifying_key().to_bytes().to_vec());

        let rec = IssuedLicense {
            id: "lic-m".into(),
            distributor_id: "d".into(),
            subscription_id: "dist-m-1".into(),
            customer_id: "dist-m".into(),
            tier: "oem".into(),
            machine_fingerprint: "fp".into(),
            issued_at: Utc::now().to_rfc3339(),
            expires_at: (Utc::now() + chrono::Duration::days(365)).to_rfc3339(),
            status: "active".into(),
            revoked_at: None,
            license_blob: "blob".into(),
            last_refresh_at: None,
        };
        assert!(resign_license_for_refresh(&seed, &registry, &rec).is_err());
    }

    #[test]
    fn issuer_seed_is_trusted_only_for_paired_key() {
        // The genuine issuer seed (its pubkey is trusted under "v2") is trusted.
        let signing = SigningKey::generate(&mut OsRng);
        let seed: [u8; 32] = signing.to_bytes();
        let registry =
            PublicKeyRegistry::new().with_key("v2", signing.verifying_key().to_bytes().to_vec());
        assert!(issuer_seed_is_trusted(&seed, &registry));

        // A random/attacker-controlled seed (customer faking issuer_key_path)
        // derives an untrusted pubkey → NOT a system instance (fail-closed).
        let attacker: [u8; 32] = SigningKey::generate(&mut OsRng).to_bytes();
        assert!(!issuer_seed_is_trusted(&attacker, &registry));

        // Empty registry (no baked key) → never trusted.
        assert!(!issuer_seed_is_trusted(&seed, &PublicKeyRegistry::new()));
    }

    #[test]
    fn load_seed_rejects_bad_format() {
        let dir = tempdir().unwrap();
        let bad = dir.path().join("bad.key");
        std::fs::write(&bad, "not-base64-!!!").unwrap();
        assert!(load_issuer_signing_seed(&bad).is_err());

        let short = dir.path().join("short.key");
        std::fs::write(&short, BASE64.encode([0u8; 16])).unwrap();
        assert!(load_issuer_signing_seed(&short).is_err());

        // A valid 32-byte seed loads.
        let good = dir.path().join("good.key");
        std::fs::write(&good, BASE64.encode([7u8; 32])).unwrap();
        assert_eq!(load_issuer_signing_seed(&good).unwrap(), [7u8; 32]);
    }
}
