//! SQLite-backed persistent store for the Partner Portal.
//!
//! Two tables:
//!   - `partner_profile` (singleton row keyed by id='singleton') — tier, company,
//!     partner_id, certification timestamp.
//!   - `partner_customers` — activated licences, status, commission (cents).
//!
//! Stats (total_sold, active_customers, this-month / lifetime commission) are
//! **computed** from `partner_customers`, never stored directly.
//!
//! Mirrors the style of [`crate::task_store`]: rusqlite, per-call connection
//! borrowed from an internal Mutex, `CREATE TABLE IF NOT EXISTS` on first open,
//! owner-only file permissions on unix (via `duduclaw_core::platform`).

use std::path::{Path, PathBuf};

use chrono::{Datelike, Utc};
use rusqlite::{params, Connection, OptionalExtension};
use serde::{Deserialize, Serialize};

// ── Data types ──────────────────────────────────────────────

/// Full partner profile row (what the UI reads).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartnerProfile {
    pub company: Option<String>,
    pub tier: String,
    pub partner_id: Option<String>,
    pub certified_at: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}

impl PartnerProfile {
    /// Default/empty profile returned when no singleton row exists yet.
    fn empty() -> Self {
        let now = Utc::now().to_rfc3339();
        Self {
            company: None,
            tier: "standard".to_string(),
            partner_id: None,
            certified_at: None,
            created_at: now.clone(),
            updated_at: now,
        }
    }
}

/// Upsert payload for `partner_profile`. Timestamps are handled by the store.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartnerProfileInput {
    pub company: Option<String>,
    pub tier: String,
    pub partner_id: Option<String>,
    pub certified_at: Option<String>,
}

/// Customer row.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartnerCustomer {
    pub id: String,
    pub name: String,
    pub tier: String,
    pub activated_at: String,
    pub status: String,
    pub commission_cents: i64,
    pub notes: Option<String>,
    pub created_at: String,
}

/// Insert payload for a customer. `id` + `created_at` are generated by the store.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartnerCustomerInput {
    pub name: String,
    pub tier: String,
    pub activated_at: String,
    pub status: String,
    #[serde(default)]
    pub commission_cents: i64,
    #[serde(default)]
    pub notes: Option<String>,
}

/// Partial-update payload for a customer. Any `Some` field overwrites;
/// `None` leaves the existing value alone.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PartnerCustomerPatch {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tier: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub activated_at: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub commission_cents: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

/// Computed sales/commission rollup.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct PartnerStats {
    pub total_sold: u64,
    pub active_customers: u64,
    pub this_month_commission_cents: i64,
    pub lifetime_commission_cents: i64,
}

// ── Store ───────────────────────────────────────────────────

/// Per-request opened SQLite store. Inexpensive to construct — mirrors the
/// "open a fresh store per RPC" pattern used elsewhere in the gateway for
/// small, low-traffic data (partner portal is a single-user admin surface).
pub struct PartnerStore {
    db_path: PathBuf,
}

impl PartnerStore {
    /// Open (or create) the partner.db at the given path and ensure schema
    /// exists. Swallows errors from `set_owner_only` (best-effort on unix,
    /// no-op on Windows — same as other stores).
    pub fn new(db_path: &Path) -> Self {
        // Ensure parent dir exists — matches how other stores behave when
        // `home_dir` is freshly created by the gateway.
        if let Some(parent) = db_path.parent() {
            let _ = std::fs::create_dir_all(parent);
        }

        // Best effort — an init failure here would be caught by the first
        // operation below, and the handler layer surfaces those errors.
        if let Ok(conn) = Connection::open(db_path) {
            let _ = Self::init_schema(&conn);
        }
        // Owner-only permissions (no-op on Windows).
        let _ = duduclaw_core::platform::set_owner_only(db_path);

        Self {
            db_path: db_path.to_path_buf(),
        }
    }

    fn open_conn(&self) -> Result<Connection, String> {
        let conn = Connection::open(&self.db_path)
            .map_err(|e| format!("open partner store: {e}"))?;
        // Busy timeout keeps short writes resilient against concurrent readers.
        conn.busy_timeout(std::time::Duration::from_secs(5))
            .map_err(|e| format!("busy_timeout: {e}"))?;
        Ok(conn)
    }

    fn init_schema(conn: &Connection) -> Result<(), String> {
        conn.execute_batch(
            "PRAGMA journal_mode=WAL;
             PRAGMA busy_timeout=5000;

             CREATE TABLE IF NOT EXISTS partner_profile (
                 id            TEXT PRIMARY KEY CHECK (id = 'singleton'),
                 company       TEXT,
                 tier          TEXT NOT NULL DEFAULT 'standard',
                 partner_id    TEXT,
                 certified_at  TEXT,
                 created_at    TEXT NOT NULL,
                 updated_at    TEXT NOT NULL
             );

             CREATE TABLE IF NOT EXISTS partner_customers (
                 id               TEXT PRIMARY KEY,
                 name             TEXT NOT NULL,
                 tier             TEXT NOT NULL,
                 activated_at     TEXT NOT NULL,
                 status           TEXT NOT NULL,
                 commission_cents INTEGER NOT NULL DEFAULT 0,
                 notes            TEXT,
                 created_at       TEXT NOT NULL
             );

             CREATE INDEX IF NOT EXISTS idx_partner_customers_status
                 ON partner_customers(status);",
        )
        .map_err(|e| format!("init partner store schema: {e}"))?;
        Ok(())
    }

    // ── Profile ─────────────────────────────────────────────

    /// Returns the singleton profile. If no row exists, returns a fresh
    /// default-empty profile WITHOUT inserting — callers (the UI) use the
    /// missing `company` as the signal to show the onboarding form.
    pub fn get_profile(&self) -> PartnerProfile {
        let conn = match self.open_conn() {
            Ok(c) => c,
            Err(_) => return PartnerProfile::empty(),
        };
        let row = conn
            .query_row(
                "SELECT company, tier, partner_id, certified_at, created_at, updated_at
                 FROM partner_profile WHERE id = 'singleton'",
                [],
                |row| {
                    Ok(PartnerProfile {
                        company: row.get(0)?,
                        tier: row.get(1)?,
                        partner_id: row.get(2)?,
                        certified_at: row.get(3)?,
                        created_at: row.get(4)?,
                        updated_at: row.get(5)?,
                    })
                },
            )
            .optional()
            .ok()
            .flatten();
        row.unwrap_or_else(PartnerProfile::empty)
    }

    /// Upsert the singleton profile row.
    pub fn upsert_profile(&self, p: &PartnerProfileInput) -> Result<(), String> {
        let conn = self.open_conn()?;
        let now = Utc::now().to_rfc3339();
        // `ON CONFLICT` keeps `created_at` stable on updates.
        conn.execute(
            "INSERT INTO partner_profile
                (id, company, tier, partner_id, certified_at, created_at, updated_at)
             VALUES ('singleton', ?1, ?2, ?3, ?4, ?5, ?5)
             ON CONFLICT(id) DO UPDATE SET
                company      = excluded.company,
                tier         = excluded.tier,
                partner_id   = excluded.partner_id,
                certified_at = excluded.certified_at,
                updated_at   = excluded.updated_at",
            params![p.company, p.tier, p.partner_id, p.certified_at, now],
        )
        .map_err(|e| format!("upsert profile: {e}"))?;
        Ok(())
    }

    // ── Customers ───────────────────────────────────────────

    /// List customers, newest first. Optionally filter by `status`.
    pub fn list_customers(
        &self,
        status_filter: Option<&str>,
        limit: usize,
    ) -> Vec<PartnerCustomer> {
        let conn = match self.open_conn() {
            Ok(c) => c,
            Err(_) => return Vec::new(),
        };
        let (sql, bind): (String, Vec<String>) = match status_filter {
            Some(s) => (
                "SELECT id, name, tier, activated_at, status, commission_cents, notes, created_at
                 FROM partner_customers
                 WHERE status = ?1
                 ORDER BY created_at DESC
                 LIMIT ?2"
                    .to_string(),
                vec![s.to_string(), limit.to_string()],
            ),
            None => (
                "SELECT id, name, tier, activated_at, status, commission_cents, notes, created_at
                 FROM partner_customers
                 ORDER BY created_at DESC
                 LIMIT ?1"
                    .to_string(),
                vec![limit.to_string()],
            ),
        };

        let mut stmt = match conn.prepare(&sql) {
            Ok(s) => s,
            Err(_) => return Vec::new(),
        };
        let binds_ref: Vec<&dyn rusqlite::types::ToSql> =
            bind.iter().map(|s| s as &dyn rusqlite::types::ToSql).collect();

        let rows = stmt
            .query_map(binds_ref.as_slice(), row_to_customer)
            .ok();
        match rows {
            Some(iter) => iter.filter_map(Result::ok).collect(),
            None => Vec::new(),
        }
    }

    /// Insert a new customer. Returns the generated UUID.
    pub fn add_customer(&self, c: &PartnerCustomerInput) -> Result<String, String> {
        if c.name.trim().is_empty() {
            return Err("name is required".to_string());
        }
        if c.tier.trim().is_empty() {
            return Err("tier is required".to_string());
        }
        if c.status.trim().is_empty() {
            return Err("status is required".to_string());
        }

        let conn = self.open_conn()?;
        let id = uuid::Uuid::new_v4().to_string();
        let created_at = Utc::now().to_rfc3339();
        conn.execute(
            "INSERT INTO partner_customers
                (id, name, tier, activated_at, status, commission_cents, notes, created_at)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)",
            params![
                id,
                c.name,
                c.tier,
                c.activated_at,
                c.status,
                c.commission_cents,
                c.notes,
                created_at,
            ],
        )
        .map_err(|e| format!("insert customer: {e}"))?;
        Ok(id)
    }

    /// Patch only the fields set to `Some` in `patch`.
    pub fn update_customer(
        &self,
        id: &str,
        patch: &PartnerCustomerPatch,
    ) -> Result<(), String> {
        let conn = self.open_conn()?;

        // Build SET clause dynamically, matching the approach in task_store.
        let mut sets: Vec<String> = Vec::new();
        let mut binds: Vec<Box<dyn rusqlite::types::ToSql>> = Vec::new();

        if let Some(v) = &patch.name {
            binds.push(Box::new(v.clone()));
            sets.push(format!("name = ?{}", binds.len()));
        }
        if let Some(v) = &patch.tier {
            binds.push(Box::new(v.clone()));
            sets.push(format!("tier = ?{}", binds.len()));
        }
        if let Some(v) = &patch.activated_at {
            binds.push(Box::new(v.clone()));
            sets.push(format!("activated_at = ?{}", binds.len()));
        }
        if let Some(v) = &patch.status {
            binds.push(Box::new(v.clone()));
            sets.push(format!("status = ?{}", binds.len()));
        }
        if let Some(v) = patch.commission_cents {
            binds.push(Box::new(v));
            sets.push(format!("commission_cents = ?{}", binds.len()));
        }
        if let Some(v) = &patch.notes {
            binds.push(Box::new(v.clone()));
            sets.push(format!("notes = ?{}", binds.len()));
        }

        if sets.is_empty() {
            return Ok(()); // no-op
        }

        binds.push(Box::new(id.to_string()));
        let sql = format!(
            "UPDATE partner_customers SET {} WHERE id = ?{}",
            sets.join(", "),
            binds.len()
        );

        let params_ref: Vec<&dyn rusqlite::types::ToSql> =
            binds.iter().map(|b| b.as_ref()).collect();
        let affected = conn
            .execute(&sql, params_ref.as_slice())
            .map_err(|e| format!("update customer: {e}"))?;
        if affected == 0 {
            return Err(format!("customer '{id}' not found"));
        }
        Ok(())
    }

    pub fn delete_customer(&self, id: &str) -> Result<(), String> {
        let conn = self.open_conn()?;
        let affected = conn
            .execute("DELETE FROM partner_customers WHERE id = ?1", params![id])
            .map_err(|e| format!("delete customer: {e}"))?;
        if affected == 0 {
            return Err(format!("customer '{id}' not found"));
        }
        Ok(())
    }

    // ── Stats (computed) ────────────────────────────────────

    /// Compute aggregated stats from `partner_customers`.
    ///
    /// `this_month_commission_cents` uses the first of the current UTC month
    /// (00:00:00Z) as the inclusive lower bound; ISO-8601 lexical comparison
    /// works because `activated_at` is stored as RFC-3339 UTC.
    pub fn compute_stats(&self) -> PartnerStats {
        let conn = match self.open_conn() {
            Ok(c) => c,
            Err(_) => {
                return PartnerStats {
                    total_sold: 0,
                    active_customers: 0,
                    this_month_commission_cents: 0,
                    lifetime_commission_cents: 0,
                };
            }
        };

        let total_sold: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM partner_customers",
                [],
                |r| r.get(0),
            )
            .unwrap_or(0);
        let active_customers: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM partner_customers WHERE status = 'active'",
                [],
                |r| r.get(0),
            )
            .unwrap_or(0);
        let lifetime_commission_cents: i64 = conn
            .query_row(
                "SELECT COALESCE(SUM(commission_cents), 0) FROM partner_customers",
                [],
                |r| r.get(0),
            )
            .unwrap_or(0);

        let now = Utc::now();
        let month_start = format!(
            "{:04}-{:02}-01T00:00:00+00:00",
            now.year(),
            now.month()
        );
        let this_month_commission_cents: i64 = conn
            .query_row(
                "SELECT COALESCE(SUM(commission_cents), 0)
                 FROM partner_customers
                 WHERE activated_at >= ?1",
                params![month_start],
                |r| r.get(0),
            )
            .unwrap_or(0);

        PartnerStats {
            total_sold: total_sold.max(0) as u64,
            active_customers: active_customers.max(0) as u64,
            this_month_commission_cents,
            lifetime_commission_cents,
        }
    }
}

fn row_to_customer(row: &rusqlite::Row) -> rusqlite::Result<PartnerCustomer> {
    Ok(PartnerCustomer {
        id: row.get(0)?,
        name: row.get(1)?,
        tier: row.get(2)?,
        activated_at: row.get(3)?,
        status: row.get(4)?,
        commission_cents: row.get(5)?,
        notes: row.get(6)?,
        created_at: row.get(7)?,
    })
}

// ── Tests ───────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn make_store() -> (tempfile::TempDir, PartnerStore) {
        let dir = tempdir().unwrap();
        let path = dir.path().join("partner.db");
        let store = PartnerStore::new(&path);
        (dir, store)
    }

    #[test]
    fn profile_missing_returns_empty_without_inserting() {
        let (_dir, store) = make_store();
        let p = store.get_profile();
        assert_eq!(p.company, None);
        assert_eq!(p.tier, "standard");
        assert_eq!(p.partner_id, None);
        assert_eq!(p.certified_at, None);

        // A second call should still see no persisted row (empty was returned,
        // not inserted) — verified by the row count being zero via a raw query.
        let conn = store.open_conn().unwrap();
        let count: i64 = conn
            .query_row("SELECT COUNT(*) FROM partner_profile", [], |r| r.get(0))
            .unwrap();
        assert_eq!(count, 0);
    }

    #[test]
    fn profile_upsert_roundtrip() {
        let (_dir, store) = make_store();
        store
            .upsert_profile(&PartnerProfileInput {
                company: Some("TechBridge Solutions".into()),
                tier: "gold".into(),
                partner_id: Some("PTR-2025-0042".into()),
                certified_at: Some("2025-08-15T00:00:00+00:00".into()),
            })
            .unwrap();
        let p = store.get_profile();
        assert_eq!(p.company.as_deref(), Some("TechBridge Solutions"));
        assert_eq!(p.tier, "gold");
        assert_eq!(p.partner_id.as_deref(), Some("PTR-2025-0042"));

        // Update again — created_at stable, updated_at refreshed.
        let original_created = p.created_at.clone();
        store
            .upsert_profile(&PartnerProfileInput {
                company: Some("TechBridge v2".into()),
                tier: "platinum".into(),
                partner_id: Some("PTR-2025-0042".into()),
                certified_at: p.certified_at.clone(),
            })
            .unwrap();
        let p2 = store.get_profile();
        assert_eq!(p2.tier, "platinum");
        assert_eq!(p2.created_at, original_created);
    }

    #[test]
    fn customer_crud_roundtrip() {
        let (_dir, store) = make_store();
        let id = store
            .add_customer(&PartnerCustomerInput {
                name: "Sunrise Bakery Co.".into(),
                tier: "pro".into(),
                activated_at: "2025-11-02T00:00:00+00:00".into(),
                status: "active".into(),
                commission_cents: 1500,
                notes: None,
            })
            .unwrap();
        assert!(!id.is_empty());

        let all = store.list_customers(None, 100);
        assert_eq!(all.len(), 1);
        assert_eq!(all[0].name, "Sunrise Bakery Co.");
        assert_eq!(all[0].commission_cents, 1500);

        store
            .update_customer(
                &id,
                &PartnerCustomerPatch {
                    status: Some("expired".into()),
                    commission_cents: Some(2000),
                    ..Default::default()
                },
            )
            .unwrap();

        let only_expired = store.list_customers(Some("expired"), 100);
        assert_eq!(only_expired.len(), 1);
        assert_eq!(only_expired[0].commission_cents, 2000);

        let only_active = store.list_customers(Some("active"), 100);
        assert!(only_active.is_empty());

        store.delete_customer(&id).unwrap();
        assert!(store.list_customers(None, 100).is_empty());
    }

    #[test]
    fn compute_stats_rolls_up_correctly() {
        let (_dir, store) = make_store();

        // Build a first-of-current-month timestamp that is guaranteed to fall
        // inside the "this month" window the stats use.
        let now = Utc::now();
        let this_month = format!("{:04}-{:02}-01T10:00:00+00:00", now.year(), now.month());
        // An earlier year is guaranteed to be outside the window.
        let last_year = format!("{:04}-01-15T10:00:00+00:00", now.year() - 1);

        store
            .add_customer(&PartnerCustomerInput {
                name: "Active This Month".into(),
                tier: "pro".into(),
                activated_at: this_month.clone(),
                status: "active".into(),
                commission_cents: 1000,
                notes: None,
            })
            .unwrap();
        store
            .add_customer(&PartnerCustomerInput {
                name: "Active Last Year".into(),
                tier: "enterprise".into(),
                activated_at: last_year,
                status: "active".into(),
                commission_cents: 5000,
                notes: None,
            })
            .unwrap();
        store
            .add_customer(&PartnerCustomerInput {
                name: "Cancelled".into(),
                tier: "pro".into(),
                activated_at: this_month,
                status: "cancelled".into(),
                commission_cents: 750,
                notes: None,
            })
            .unwrap();

        let stats = store.compute_stats();
        assert_eq!(stats.total_sold, 3);
        assert_eq!(stats.active_customers, 2);
        // Both this-month rows contribute — status filter doesn't apply to
        // commission totals per the spec ("SUM(commission_cents WHERE activated_at >= first-of-month)").
        assert_eq!(stats.this_month_commission_cents, 1000 + 750);
        assert_eq!(stats.lifetime_commission_cents, 1000 + 5000 + 750);
    }
}
