#!/usr/bin/env python3
"""Regenerate duduclaw-comp-crates.inc directly from crates/duduclaw-comp/
Cargo.lock in the main repo -- unlike duduclaw-cli/duduclaw-sysd, this crate
is ALREADY a standalone cargo project (own `[workspace]` empty table, no
`version.workspace = true` shorthand -- see its own Cargo.toml comment: it
was detached from the main workspace from day one because smithay is
Linux-only), so there's no flatten-Cargo.toml step needed, only a source
copy (see refresh-src.sh) and this closure list. All 246 of its deps are
crates.io-sourced with real checksums already (verified: zero git/path
entries) -- so no cargo-vendor detour needed here, unlike duduclaw-shell.
"""
import os
import sys

try:
    import tomllib
except ImportError:
    import tomli as tomllib  # type: ignore

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.normpath(os.path.join(HERE, "..", "..", "..", ".."))
LOCK_PATH = os.path.join(HERE, "files", "duduclaw-comp-src", "Cargo.lock")
OUT_PATH = os.path.join(HERE, "duduclaw-comp-crates.inc")
ROOT_PKG = "duduclaw-comp"


def main():
    with open(LOCK_PATH, "rb") as f:
        lock = tomllib.load(f)

    entries = []
    for pkg in lock["package"]:
        if pkg["name"] == ROOT_PKG:
            continue
        src = pkg.get("source", "")
        if "crates.io" not in src:
            print(f"WARNING: non-crates.io source for {pkg['name']} {pkg['version']}: {src}",
                  file=sys.stderr)
            continue
        cksum = pkg.get("checksum")
        if not cksum:
            print(f"WARNING: no checksum for {pkg['name']} {pkg['version']}", file=sys.stderr)
        entries.append((pkg["name"], pkg["version"], cksum))

    entries.sort()

    lines = [
        "# Autogenerated by gen-crates-inc.py from files/duduclaw-comp-src/Cargo.lock\n",
        "# Re-run after refresh-src.sh whenever crates/duduclaw-comp's deps change.\n\n",
        'SRC_URI += " \\\n',
    ]
    for name, ver, _ in entries:
        lines.append(f"    crate://crates.io/{name}/{ver} \\\n")
    lines.append('"\n\n')
    for name, ver, cksum in entries:
        if cksum:
            lines.append(f'SRC_URI[{name}-{ver}.sha256sum] = "{cksum}"\n')

    with open(OUT_PATH, "w") as f:
        f.writelines(lines)

    print(f"Wrote {OUT_PATH}: {len(entries)} crates.io deps", file=sys.stderr)


if __name__ == "__main__":
    main()
