SUMMARY = "DuDuClaw agent gateway + CLI (single `duduclaw` binary)"
DESCRIPTION = "The `duduclaw` binary -- both roles the Y2-1 task brief names \
separately (\"duduclaw gateway\" and \"duduclaw-cli\") turn out to be the \
SAME ELF: duduclaw-gateway is a library crate with no [[bin]] of its own, \
duduclaw-cli's src/bin/duduclaw.rs is the only binary, and `duduclaw run` \
is what duduclaw-gateway.service execs. One recipe, one package, both jobs. \
Built --no-default-features --features duduclaw-gateway/dashboard, matching \
container/Dockerfile.server's rust-builder stage (avoids enigo/xcap and the \
wayland/pipewire/gbm pull-in the desktop feature drags in on Linux). \
Source: a mini-workspace snapshot of crates/duduclaw-cli + the 20 other \
DuDuClaw crates it reaches by path, generated by refresh-src.sh -- see that \
script's header comment for why a snapshot (not S pointed at the monorepo \
directly) and why a mini-workspace (not a single flattened crate the way \
duduclaw-sysd's recipe does it)."
HOMEPAGE = "https://github.com/duduclaw/duduclaw"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://LICENSE;md5=87e8e4a396af46e141a08fbc9f1b0455"

# Real native-dependency gap, hit by actually running do_compile:
# openssl-sys (a transitive dep of reqwest/rusqlite's tls stack -- some
# transitive dep picks openssl-sys over rustls despite rustls also being in
# the graph) needs pkg-config to find OpenSSL for the TARGET
# (x86_64-poky-linux-gnu), and neither pkg-config itself nor a target
# OpenSSL sysroot were present: "Could not run `... pkg-config --libs
# --cflags openssl`: The pkg-config command could not be found." `inherit
# pkgconfig` wires PKG_CONFIG_PATH/pkgconfig-native the standard OE way;
# `openssl` in DEPENDS populates the target recipe-sysroot with libssl/
# libcrypto + their .pc files for openssl-sys to find via pkg-config.
DEPENDS += "openssl"
inherit cargo cargo-update-recipe-crates pkgconfig

# See duduclaw-sysd's recipe for why S is UNPACKDIR- not WORKDIR-relative.
SRC_URI = "file://duduclaw-cli-src"
S = "${UNPACKDIR}/duduclaw-cli-src"

require duduclaw-cli-crates.inc

# Build only the duduclaw-cli package (bin "duduclaw") out of the mini
# workspace, not every member's own [[bin]] (duduclaw-sysd and
# duduclaw-cli-worker are also workspace members here because duduclaw-cli
# reaches them by path, but this recipe isn't the place that installs
# their binaries -- duduclaw-sysd has its own recipe already).
CARGO_SRC_DIR = "crates/duduclaw-cli"

# Appliance convention (container/Dockerfile.server's rust-builder stage):
# dashboard on, desktop off -- desktop pulls enigo/xcap, which on Linux pull
# wayland/pipewire/gbm this recipe has no business depending on.
# `app-compat` (2026-09-29, platform feature audit S15): the `duduclaw compat`
# subcommand family (compat.d runner registry + `windows-vm` RemoteApp
# bootstrap) is OS-only, so the platform binary no longer compiles it by
# default. This image DOES need it -- duduclaw-shell spawns
# `duduclaw compat windows-vm app ...` and compat.d/windows-vm.toml names it
# as its entrypoint -- hence the feature must be turned on here.
#
# NOT YET: the vendored duduclaw-cli-src snapshot predates the feature (its
# Cargo.toml has no `app-compat`), and cargo hard-fails on an unknown
# feature. When `scripts/sync-platform.sh` brings the snapshot to a platform
# version that carries it (the first release after 2026-09-29), swap the two
# lines below. Until then the snapshot still compiles `duduclaw compat`
# unconditionally, so the image is unaffected.
CARGO_BUILD_FLAGS:append = " --no-default-features --features duduclaw-gateway/dashboard"
# CARGO_BUILD_FLAGS:append = " --no-default-features --features duduclaw-gateway/dashboard,app-compat"
# 2026-09-08 (fix14 bake, twice in a row): cargo.bbclass's CARGO_BUILD_FLAGS
# carries no `-j`, so cargo spawns nproc rustc jobs regardless of
# PARALLEL_MAKE / BB_NUMBER_THREADS (neither reaches cargo). The
# duduclaw-gateway lib rustc and the duduclaw-cli rustc each need several GB;
# side by side on the 12 GB builder the kernel SIGKILLed one of them
# (`(signal: 9, SIGKILL: kill)`, cargo exit 101, no diagnostic at all) — with
# `-j 2` and with `-j 1` make flags alike. One rustc at a time for this
# megacrate; the small crates before it are cheap enough not to matter.
CARGO_BUILD_FLAGS:append = " -j 1"

# Y2-3 (2026-08-25) real fix for do_package_qa's buildpaths QA failure, hit
# by actually running bitbake:
#   "ERROR: QA Issue: File /usr/bin/duduclaw in package duduclaw-cli
#    contains reference to TMPDIR [buildpaths]"
# `strings` on the offending binary showed the leaked paths are C sources
# from a vendored crate's build.rs (tree-sitter's C runtime -- stack.c,
# tree_cursor.c, etc. -- compiled via the `cc` crate, not rustc), all
# rooted at ${WORKDIR}/sources/cargo_home/bitbake/tree-sitter-<ver>/... --
# the crate:// fetcher's unpack location (cargo-update-recipe-crates.
# bbclass), NOT ${S} or ${B}. rust-common.bbclass already remaps the
# equivalent leak on the Rust side (RUST_DEBUG_REMAP =
# "--remap-path-prefix=${WORKDIR}=${TARGET_DBGSRC_DIR}", covers the whole
# WORKDIR tree via rustc's own flag) but that flag only reaches rustc
# invocations. The C side gets DEBUG_PREFIX_MAP via cargo_common.bbclass's
# `export CFLAGS="${CFLAGS}"`, but DEBUG_PREFIX_MAP (bitbake.conf) only maps
# ${S} and ${B} specifically -- neither covers ${WORKDIR}/sources/cargo_home,
# a THIRD directory under WORKDIR that cc-rs's build script compiles from.
# Fix: mirror the same WORKDIR-wide remap Rust already gets, for CFLAGS/
# CXXFLAGS, using the same -ffile-prefix-map mechanism DEBUG_PREFIX_MAP
# itself already uses (not -fdebug-prefix-map -- -ffile-prefix-map also
# remaps __FILE__/__BASE_FILE__ macro expansions, which is what actually
# leaked here: tree-sitter's C runtime uses assert() macros that stringize
# __FILE__ into the binary's .rodata independent of any -g debug info).
# Appended after DEBUG_PREFIX_MAP's own -ffile-prefix-map=${S}=... /
# -ffile-prefix-map=${B}=... entries, so those more specific mappings still
# win for anything under S/B; this one only adds coverage for the region
# they don't reach. Verified by rebuilding and re-running do_package_qa
# after this change -- see the Y line TODO entry for the pass evidence, not
# assumed from the flag alone.
CFLAGS:append = " -ffile-prefix-map=${WORKDIR}=${TARGET_DBGSRC_DIR}"
CXXFLAGS:append = " -ffile-prefix-map=${WORKDIR}=${TARGET_DBGSRC_DIR}"

SRC_URI += "file://duduclaw-gateway.service"
SRC_URI += "file://duduclaw-home-profile.sh"

do_install:append() {
    install -d ${D}${systemd_system_unitdir}
    # UNPACKDIR, not WORKDIR -- see duduclaw-sysd's recipe for the exact
    # error this fixes (hit it for real there first).
    install -m 0644 ${UNPACKDIR}/duduclaw-gateway.service ${D}${systemd_system_unitdir}/duduclaw-gateway.service
    # Interactive-shell DUDUCLAW_HOME — see the file's own header for the
    # live-fire divergence (root CLI writing /root/.duduclaw while the
    # launcher reads /data/duduclaw) this closes.
    install -d ${D}${sysconfdir}/profile.d
    install -m 0644 ${UNPACKDIR}/duduclaw-home-profile.sh ${D}${sysconfdir}/profile.d/duduclaw-home.sh
}

inherit systemd
SYSTEMD_SERVICE:${PN} = "duduclaw-gateway.service"
SYSTEMD_AUTO_ENABLE:${PN} = "enable"

FILES:${PN} += "${systemd_system_unitdir}/duduclaw-gateway.service"
